cli/dcoscli/marathon/main.py, cli/tests/data/marathon/groups/update_good.json, cli/tests/integrations/common.py, cli/tests/integrations/test_marathon.py, cli/tests/integrations/test_marathon_groups.py, dcos/jsonitem.py, dcos/marathon.py, tests/test_jsonitem.py
Also add 'Created deployment ' message to all updates.
=> add group update

setup.py
=> fix jsonschema version bug

cli/tests/integrations/test_package.py, dcos/package.py
It was slightly confusing before
=> better uninstall message for multi-app packages

cli/dcoscli/analytics.py, cli/tests/data/dcos.toml, cli/tests/data/missing_params_dcos.toml
=> fix analytics to use actual subcommand

dcos/subcommand.py
The previous message was not very helpful
=> improved the package uninstall failure message

cli/dcoscli/marathon/main.py, dcos/marathon.py
If old marathon version, use the cli's json-schema for now.
=> dcos-447 read json-schema from Marathon

cli/dcoscli/service/main.py, cli/dcoscli/task/main.py, cli/setup.py, cli/tests/data/file/follow.json, cli/tests/data/file/two_tasks.json, cli/tests/data/file/two_tasks_follow.json, cli/tests/data/marathon/sleep2.json, cli/tests/fixtures/service.py, cli/tests/fixtures/task.py, cli/tests/integrations/common.py, cli/tests/integrations/test_dcos.py, cli/tests/integrations/test_help.py, cli/tests/integrations/test_marathon.py, cli/tests/integrations/test_service.py, cli/tests/integrations/test_task.py, dcos/http.py, dcos/marathon.py, dcos/mesos.py, dcos/package.py, dcos/util.py
This is missing tests.  I figured I'd go ahead and get the conversation started while I write the tests, then we can review tests separately later (part of the same PR, of course).  
Tomorrow (5/22), I'll mark this up with comments describing some of my design decisions.
=> dcos tail -- DCOS-1133

cli/setup.py
=> Use virtualenv 13 for newer pip

cli/dcoscli/help/main.py, cli/tests/integrations/test_help.py
dcos help <subcommand> should be aliased to dcos <subcommand> --help
=> [ADD] DCOS-1323 

cli/dcoscli/help/main.py, cli/tests/integrations/test_help.py
Reverts mesosphere/dcos-cli#240
=> Revert "[ADD] DCOS-1323 "

cli/dcoscli/marathon/main.py
This fixes bug found by intercom user: https://app.intercom.io/a/apps/wn4z9z0y/inbox/conversation/997828033
=> clean up lastTaskFailure for schema validation

cli/dcoscli/analytics.py, cli/tests/integrations/test_analytics.py
set read timeout and connect timeout
=> DCOS-1762 hopefully this fixes CLI commands hanging

cli/dcoscli/marathon/main.py, cli/tests/integrations/test_marathon.py, dcos/marathon.py
Reverts mesosphere/dcos-cli#262
=> Revert "[ADD] DCOS-367 As a user, I want to scale the application"

bin/install/install-dcos-cli.sh, cli/dcoscli/data/config-schema/core.json, cli/tests/data/dcos.toml, cli/tests/integrations/test_config.py, dcos/http.py, dcos/marathon.py, dcos/mesos.py, win_bin/install/install-dcos-cli.ps1
=> add configurable timeout

cli/dcoscli/node/main.py, cli/dcoscli/service/main.py, cli/tests/integrations/common.py, cli/tests/integrations/test_node.py, cli/tests/integrations/test_service.py, dcos/util.py
marathon` to help the user debug SSH issues
=> [DCOS-2402] Prints the ssh command used in `dcos node ssh` and `dcos service log

cli/dcoscli/analytics.py, cli/dcoscli/node/main.py, cli/tests/integrations/test_node.py, cli/tests/integrations/test_service.py, dcos/emitting.py
I figured out why that last PR wasn't testable (stderr flush issue).  totally wasn't worth the ~5 hours of debugging time, but oh well.
=> Added tests for ssh connect message.

dcos/http.py
fixes this: https://rollbar.com/thomas-mesosphere/dcos/items/1561/?item_page=0&#instances
=> Added requests.exceptions.RequestException handling

dcos/util.py
Fixes: https://rollbar.com/thomas-mesosphere/dcos/items/1609/occurrences/6946794856/
=> Added exception handling for directory permission errors

dcos/mesos.py
fixes: https://rollbar.com/thomas-mesosphere/dcos/items/1543/occurrences/6961996376/
=> Fixed slave id access

cli/dcoscli/analytics.py
Verified that the value gets sent by doing manual tests.
=> DCOS-2262 Send hostname segment.io track events

cli/dcoscli/marathon/main.py, cli/tests/integrations/test_marathon.py
Fixed my errors from #353 . Hopefully I have not introduced new ones.
Thanks.
=> Revert incorrect example text from code and test

dcos/mesos.py
The Mesos API removed /shutdown as of 0.24. This fix will try /teardown first and then /shutdown if /teardown returns a 404.
=> Add exception catching for /shutdown.

bin/install/install-optout-dcos-cli.sh
Don't merge yet as I am testing this manually but you can start the review. I changed/added lines 112-113. cc @pyronicide
=> Provide opt-out install script

bin/install/install-dcos-cli.sh, bin/install/install-optout-dcos-cli.sh
=> Make a more useful error message when virtualenv isn't installed

Dockerfile.cosmos
ran this locally, finished quickly!
=> add dockerfile for cosmos CI (adding java)

cli/dcoscli/package/main.py, dcos/package.py
This works with the helloworld package only right now.
=> install using cosmos server

cli/dcoscli/package/main.py, cli/tests/integrations/test_package.py, dcos/constants.py, dcos/cosmospackage.py
https://github.com/mesosphere/dcos-cli/issues/436
=> discover cosmos

cli/dcoscli/data/config-schema/package.json, cli/dcoscli/package/main.py, cli/tests/integrations/test_config.py
=> add package.cosmos_url override config value

bin/install/install-dcos-cli.sh, bin/install/legacy/install-legacy-dcos-cli.sh, bin/install/legacy/install-legacy-optout-dcos-cli.sh, bin/install/upload_to_s3.sh, win_bin/install/legacy/install-legacy-dcos-cli.ps1
=> remove package configuration from install script

dcos/http.py
=> add a helpful message when a response returns a 403

cli/dcoscli/package/main.py, dcos/cosmospackage.py
=> error if user runs legacy cli with cosmos enabled dcos

cli/dcoscli/data/help/package.txt, cli/dcoscli/package/main.py, cli/tests/data/help/package.txt, cli/tests/data/package/json/test_repo_list.json, cli/tests/integrations/test_package.py, dcos/cosmospackage.py
=> add --json option for `dcos package repo list`

cli/dcoscli/data/help/package.txt, cli/dcoscli/package/main.py, cli/tests/data/help/package.txt, cli/tests/integrations/test_package.py, dcos/cosmospackage.py
=> update `dcos package repo remove` to only take repo-name as paramater

cli/tests/integrations/test_service.py
Since we now have two version in the repo.
=> allows use same cassandra framework in test

bin/install/install-dcos-cli.sh, bin/install/install-optout-dcos-cli.sh
All DCOS clusters currently download the latest `install.sh`. When we introduce backward incompatabilities, this ends up creating a less than ideal user experience. By checking the version of the cluster, we're able to install the correct CLI version for the cluster. This is a somewhat temporary fix and we'll design a more permanent one later.
=> Adding version checking to the install script.

dcos/http.py
We use the private `_request` method for acs auth login which doesn't have the ssl check in the main `request` method, so we need to add that check for that request.
=> add ssl verification for acs auth login

cli/dcoscli/data/help/node.txt, cli/dcoscli/node/main.py, cli/tests/data/help/node.txt, cli/tests/integrations/test_node.py
See https://mesosphere.atlassian.net/browse/DCOS-5441.
=> Rename `node --master` -> `node --leader`

cli/dcoscli/analytics.py, cli/tests/data/analytics/dcos_reporting.toml, cli/tests/integrations/test_analytics.py
=> don't send core.dcos_acs_token to segment.io

dcos/cosmospackage.py, dcos/errors.py
=> be more accurate when checking if cosmos enabled

cli/dcoscli/main.py, cli/tests/integrations/test_dcos.py
=> add DCOS version to `dcos --version`

ccm/delete_ccm_cluster.sh, ccm/start_ccm_cluster.sh, ccm/tests_ccm_cluster.sh, ccm/wait_for_ccm_cluster.sh
So that we don't print secrets in CI
=> remove -x from CI helper scripts

dcos/subcommand.py
=> improve virtualenv missing message

ISSUE_TEMPLATE.md
=> update ISSUE_TEMPLATE after `dcos --version` change

cli/dcoscli/data/help/dcos.txt, cli/tests/data/help/dcos.txt
=> remove extra space in `dcos --help`

cli/tests/integrations/test_node.py, cli/tests/unit/test_task.py, dcos/mesos.py
Added condition to address when mesos_master_url is provided in get_dcos_url.
Fixed exception statement in get_dcos_url.
=> Address missing core.dcos_url when mesos_master_url  is provided

cli/dcoscli/data/help/auth.txt, cli/dcoscli/data/help/config.txt, cli/dcoscli/data/help/help.txt, cli/dcoscli/data/help/marathon.txt, cli/dcoscli/data/help/node.txt, cli/dcoscli/data/help/package.txt, cli/dcoscli/data/help/service.txt, cli/dcoscli/data/help/task.txt, cli/tests/data/help/auth.txt, cli/tests/data/help/config.txt, cli/tests/data/help/help.txt, cli/tests/data/help/marathon.txt, cli/tests/data/help/node.txt, cli/tests/data/help/package.txt, cli/tests/data/help/service.txt, cli/tests/data/help/task.txt
=> add --help to usage information

dcos/subcommand.py
=> verify virtualenv version before installing subcommand

cli/dcoscli/subcommand.py
=> remove code duplication

cli/dcoscli/task/main.py, cli/tests/integrations/test_task.py
=> handle multiple tasks in `task ls`

dcos/emitting.py
=> use vanilla less for default pager

cli/tests/unit/test_task.py, dcos/config.py, dcos/util.py
=> enforce 600 (owner only) permission on config file

bin/env.sh, cli/bin/env.sh, cli/tests/integrations/common.py
- Explicit version for pyvenv executable
- Increase sleep time for SSH to accomodate remote clients
=> Test tweaks

dcos/subcommand.py, dcos/util.py
unset env var to specify correct virtualenv and override: https://github.com/pypa/setuptools/blob/ac325f34b73c534fd19204400afa598bf63ea301/setuptools/command/easy_install.py#L1940
=> handle darwin bug with PYVENV_LAUNCHER env var

cli/dcoscli/package/main.py, dcos/cosmospackage.py
Fixes #712.
~~Depends on #726. **Do not merge before that!**~~
=> Remove extra call to the Cosmos /package/render endpoint

cli/dcoscli/help/main.py, cli/dcoscli/node/main.py, cli/dcoscli/service/main.py, dcos/subcommand.py, dcos/subprocess.py, dcos/util.py
Due to bugs in pyinstaller and setuptools we need to modify the
environment when forking a command.
=> add Subproc class to handle env change needed for subprocess

cli/dcoscli/data/help/marathon.txt, cli/dcoscli/marathon/main.py, cli/tests/data/help/marathon.txt, cli/tests/data/marathon/pods/double.json, cli/tests/data/marathon/pods/doubleplusgood.json, cli/tests/data/marathon/pods/good.json, cli/tests/data/marathon/pods/updated_good.json
Get the remaining pod commands stubbed out so that the integration tests are actually invoking the command methods.
=> Preparation for working integration tests

cli/tests/integrations/test_marathon.py, dcos/marathon.py, tests/test_marathon.py
Per our discussion on Friday @tamarrow. Open to suggestions on the wording.
=> Change 409 response status error message to be more understandable

cli/dcoscli/tables.py, cli/tests/fixtures/marathon.py, cli/tests/unit/data/deployment.txt, cli/tests/unit/data/deployment/app.txt, cli/tests/unit/data/deployment/pod.txt, cli/tests/unit/test_tables.py
- Add a new POD column to the table from "affectedPods" field
- Correctly handle the occurrence of "app" xor "pod" in actions
=> Support pods in the `marathon deployment list` table view

dcos/marathon.py
PR on top of pods branch due to merge conflicts.
=>  log marathon error message for debugging

dcos/http.py
=> improve message prompting for auth token

cli/dcoscli/tables.py, cli/tests/integrations/test_marathon_pod.py, cli/tests/unit/data/pod.txt, cli/tests/unit/data/pod_without_instances.txt, cli/tests/unit/data/pod_without_spec_version.txt
=> Refer to TASKS in `pod list` table, instead of CONTAINERS

cli/tests/data/package/json/test_describe_app_options.json, cli/tests/data/package/json/test_describe_marathon_app_render.json, cli/tests/data/package/json/test_repo_list.json, cli/tests/data/universe-v3-stub.json, cli/tests/integrations/test_package.py, cli/tests/integrations/test_service.py
=> update tests to use universe v3

cli/dcoscli/task/main.py, dcos/mesos.py
=> handle `dcos task` commands when no task is given

cli/dcoscli/job/main.py, cli/tests/integrations/test_job.py
better error handling.  do not expose 404 issues to cli users.
=> Improved Error handling Jobs

cli/tests/integrations/common.py, cli/tests/integrations/test_marathon_pod.py, cli/tests/integrations/test_task.py, cli/tests/unit/data/helloworld-resource.json, dcos/mesos.py
https://mesosphere.atlassian.net/browse/DCOS-10828
=> pods: read from task log not executor

dcos/mesos.py
=> mesos: remove unused function `slave_base_url`

cli/dcoscli/job/main.py, cli/tests/data/dcos.toml, cli/tests/integrations/test_job.py, dcos/marathon.py, dcos/metronome.py, dcos/rpcclient.py, tests/test_marathon.py
Created metronome class wrapper similar to marathon
=> metronome class

cli/dcoscli/job/main.py, cli/tests/integrations/test_marathon.py, dcos/errors.py, dcos/http.py
add disk to json if not provided.  
provide back meaningful message for json processing failures.
=> better reporting of json processing failures for metronome

cli/dcoscli/log.py, cli/dcoscli/task/main.py, cli/tests/data/marathon/pods/double.json, cli/tests/data/marathon/pods/doubleplusgood.json, cli/tests/data/marathon/pods/good_status.json, cli/tests/integrations/common.py, cli/tests/integrations/test_marathon.py, cli/tests/integrations/test_marathon_debug.py, cli/tests/integrations/test_marathon_pod.py, cli/tests/integrations/test_service.py, cli/tests/integrations/test_task.py
=> Remove skips for pods tests and a test affected by a Marathon bug

dcos/mesos.py
With the new semantics, an ATTACH_CONTAINER_INPUT call will be attempted
once before committing to a persistent connection where the actual input
is streamed to the agent.
This change is required to get around a limitation of the python client
libraries where an HTTP response is not read until after the entire
request is sent. IN our case, we *never* complete the request (until a
timeout), so we don't see the proper error unless we do things as
updated in this commit.
=> Updated `dcos task exec` ATTACH_CONTAINER_INPUT semantics.

cli/dcoscli/data/help/auth.txt, cli/tests/data/help/auth.txt, cli/tests/unit/data/auth_provider.txt, dcos/auth.py
Amended https://github.com/dcos/dcos-cli/pull/861 to fix tests
=> auth: grammar edits from @joel-hamill

ccm/start_ccm_cluster.sh
This is the first step towards https://mesosphere.atlassian.net/browse/DCOS-11989
=> Change cf template name to cf template url

Dockerfile.test, README.rst, bin/env.sh, cli/bin/env.sh, cli/binary/Dockerfile.linux-binary, cli/setup.py, cli/tox.ini, cli/tox.win.ini, setup.py, tox.ini, tox.win.ini
Waiting on updates to Windows CI.
=> python35: update as supported version (bump from 3.4)

cli/dcoscli/log.py
related changes:
- [dcos](https://github.com/dcos/dcos/pull/1122)
- [dcos-ee](https://github.com/mesosphere/dcos-enterprise/pull/494)
- [dcos-log](https://github.com/dcos/dcos-log/pull/29)
- [ui] TBD
=> update log entry format

cli/tests/integrations/test_config.py, dcos/jsonitem.py, tests/test_jsonitem.py
=> config: default `core.dcos_url` scheme to https

cli/dcoscli/data/help/job.txt, cli/tests/data/help/job.txt
it is part of the docopt magic
=> `dcos job` without subcommands will now bring usage information

dcos/mesos.py
This PR is dependent on https://github.com/dcos/dcos/pull/1179
It should not be merged until this PR has landed.
=> Updated HTTP headers for `dcos task exec` based on Mesos changes.

cli/dcoscli/data/help/config.txt
Added the `dcos config set` options in the help.
=> Add available config properties

dcos/mesos.py
Running `dcose task exec` against containers launched by the docker
containerizer is currently unsupported. This commits prints a better
error message when attempting to run this command against such a
container.
=> Updated 'dcos task exec' to print better error message.

cli/dcoscli/config/main.py, dcos/config.py
$ DCOS_URL=http://loalhost dcos --log-level=debug config show
core.dcos_acs_token ********
core.dcos_url http://loalhost       # overwritten by environment var DCOS_URL; config file value: http://52.10.13.118/
=> config: change show config to communicate env var overwrites

dcos/auth.py
with `webbrowser.open`
so it's one less thing for the user to do and a tad quicker and easier to login.
https://www.screencast.com/t/frNtgtXShD1i
Cc: @matthewdfuller
=> `dcos auth login`: Automatically open token page

cli/dcoscli/tables.py
Before:
After:
Cc: @tamarrow, @ssk2
=> Truncate description in package list

cli/dcoscli/data/help/task.txt, cli/dcoscli/task/main.py, cli/tests/data/marathon/apps/sleep-completed.json, cli/tests/integrations/test_task.py, dcos/mesos.py
Update `dcos task` only shows active tasks, `--completed` flag to only
show completed tasks and `--all` to show all tasks.
=> task: clean up `dcos task`

cli/dcoscli/data/help/package.txt, cli/dcoscli/package/main.py
which allows importing multiple repos from a JSON file.
It accepts the same JSON file format that is generated by `dcos package list --json`, so that means that you can use `dcos package list --json` to make a backup of your repository configuration and `dcos package repo import` to restore from that backup. E.g.:
```
$ dcos package repo list
Universe fork: https://s3.amazonaws.com/abramowi-sandbox-ue1-a-shared/my-universe-fork
ethos-core-universe: https://dcos-private-universe.s3.amazonaws.com/ethos/1.0/unstable/repo/repo-up-to-1.8.json
Universe: https://universe.mesosphere.com/repo
$ dcos package repo list --json > dcos-repos.json
$ cat dcos-repos.json
{
"repositories": [
{
"name": "Universe fork",
"uri": "https://s3.amazonaws.com/abramowi-sandbox-ue1-a-shared/my-universe-fork"
},
{ …
```
=> Add `dcos package repo import`

cli/dcoscli/data/help/dcos.txt, dcos/config.py, dcos/constants.py, dcos/subcommand.py
https://jira.mesosphere.com/browse/DCOS-14331
I'm intentionally targeting master with this pr.
=> config: add DCOS_DIR env var

cli/dcoscli/main.py, dcos/cluster.py, dcos/config.py, dcos/constants.py
https://jira.mesosphere.com/browse/DCOS-14316
=> cluster: move global config to cluster config

README.rst, cli/bin/test.sh, cli/dcoscli/main.py, cli/tests/data/config/invalid_section.toml, cli/tests/data/config/parse_error.toml, cli/tests/integrations/test_auth.py, cli/tests/integrations/test_config.py, cli/tests/integrations/test_job.py, cli/tests/integrations/test_marathon.py, cli/tests/integrations/test_package.py, cli/tests/integrations/test_ssl.py, dcos/cluster.py, dcos/config.py
https://jira.mesosphere.com/browse/DCOS-14319
This is on top of #938
=> Cluster config

cli/dcoscli/log.py, cli/dcoscli/node/main.py
- fix typo
- replace KeyError with a broader Exception
- remove stale comments
=> minor clean up

cli/tests/integrations/test_package.py, dcos/http.py
https://jira.mesosphere.com/browse/DCOS_OSS-1029
=> http: send auth token for requests matching package.cosmos_url

cli/dcoscli/package/main.py, cli/tests/data/marathon/apps/app_add_400.json, cli/tests/data/marathon/groups/complicated.json, cli/tests/data/marathon/groups/complicated_bad.json, cli/tests/data/marathon/groups/good.json, cli/tests/data/marathon/groups/scale.json, cli/tests/data/package/json/test_describe_marathon.json, cli/tests/data/package/json/test_describe_marathon_package_version.json, cli/tests/data/package/json/test_list_helloworld.json, cli/tests/data/package/json/test_list_helloworld_cli.json, cli/tests/data/package/json/test_package_metadata.json, cli/tests/integrations/test_marathon.py, cli/tests/integrations/test_marathon_groups.py, cli/tests/integrations/test_package.py, cli/tests/integrations/test_task.py, dcos/package.py, dcos/packagemanager.py
A number of marathon tests were failing on windows and blocking PRs from being merged. After looking at the tests and fixing them, it's not clear how they were ever working (even on linux/mac). I've updated them to be more stable both on linux/mac and on windows.
After fixing these issues, I noticed a bunch of other integration tests were failing as well. This PR is attempting to address all of these outstanding failing tests and turn them all green again.
=> Fixed broken integration tests.

cli/dcoscli/data/help/package.txt, cli/dcoscli/package/main.py, cli/dcoscli/util.py, cli/tests/integrations/helpers/package.py, cli/tests/integrations/test_experimental.py, cli/tests/integrations/test_package.py, cli/tests/integrations/test_service.py, cli/tests/integrations/test_task.py, cli/tests/unit/test_package_uninstall.py
WIP. Creating to run integration tests.
=> [INFINITY-1586] User must type name of service to confirm uninstall

cli/dcoscli/package/main.py, cli/tests/integrations/test_package.py
https://jira.mesosphere.com/browse/DCOS-16434
=> Add disclaimer during install

cli/dcoscli/package/main.py, cli/tests/integrations/test_package.py
-Added warning message about the planned deprecation for appid in `dcos package install`
=> package install appid planned deprecation warning

dcos/http.py
Otherwise, when a cluster is configured with a custom CA path, it will
try to use it instead of the system's CA bundle and external requests
will fail.
In such cases, setting it to None will let the requests package enabling
it by default.
=> [DCOS_OSS-618] Ignore core.ssl_verify for external requests

cli/tests/integrations/test_cluster.py
While they were passing independently, the combination of #1015 and #1036 broke the CI.
This PR refactors the failing test a bit, mainly to get the current config dir before setting the DCOS_DIR env variable.
=> Update test_remove_all which was failing after #1036

dcos/packagemanager.py
Fixes https://jira.mesosphere.com/browse/COPS-2067
=> Add missing case to cosmos error handling

cli/dcoscli/auth/main.py, cli/dcoscli/cluster/main.py, cli/dcoscli/data/help/cluster_ee.txt, cli/dcoscli/tables.py, cli/dcoscli/test/common.py, cli/dcoscli/util.py, cli/tests/fixtures/clusters.py, cli/tests/integrations/test_cluster.py, cli/tests/integrations/test_cluster_migration.py, cli/tests/unit/data/auth_provider.txt, cli/tests/unit/data/cluster.txt, cli/tests/unit/test_cluster.py, cli/tests/unit/test_util.py, dcos/auth.py, dcos/cluster.py, dcos/emitting.py
This introduces a link and unlink subcommand which allow to link clusters together.
This is a new feature in DC/OS EE 1.11.
=> Linked clusters

cli/dcoscli/cluster/main.py
When converting a Cluster into a dict, an HTTP request is being made in order to get the cluster version.
This makes use of Python's `concurrent.futures` module to trigger requests asynchronously.
=> Make concurrent requests when listing clusters

cli/dcoscli/log.py, cli/tests/integrations/test_node.py, cli/tests/integrations/test_task.py, cli/tests/unit/test_node.py, cli/tests/unit/test_task.py
blocked by
- [dcos-log](https://github.com/dcos/dcos-log/pull/47)
- [oss dcos](https://github.com/dcos/dcos/pull/2183)
- [ee dcos](https://github.com/mesosphere/dcos-enterprise/pull/1854)
- [oss dcos](https://github.com/dcos/dcos/pull/2224)
=> fix dcos-log integration tests

cli/tests/integrations/test_ssl.py, dcos/data/config-schema/core.json
Give more context regarding the certificates used if the value of `ssl_verify` is set to `True`.
=> Updated description of ssl_verify.

ci/Jenkinsfile-linux-integration, ci/Jenkinsfile-mac-integration, ci/Jenkinsfile-windows-integration, cli/tests/integrations/test_marathon.py
This backports recent CI fixes in master to 0.6.x.
=> 0.6.x CI fixes

python/lib/dcos/dcos/cluster.py, python/lib/dcos/tests/test_cluster.py, python/lib/dcoscli/dcoscli/cluster/main.py, python/lib/dcoscli/tests/integrations/test_service.py
- Use a variable in a test
- Use a try / except / else clause 
- Revert "Moved cluster attachment to not lose track of attached cluster."
=> Improvements

pkg/config/config.go, pkg/httpclient/client.go, pkg/httpclient/client_test.go
- Move trailing slash trim to the config package
- Remove named return values
- Update httpclient tests (add tests for TLS and the timeout)
=> httpclient updates

pkg/httpclient/client.go, pkg/httpclient/client_test.go
Using functional options gives more flexibility and removes the dependency with the config package.
This would be needed when creating HTTP clients from a custom `marathon.url` or when there is no config yet (eg. during cluster setup).
=> Create the HTTP client based on functional options

pkg/cmd/dcos_cluster.go, pkg/cmd/dcos_cluster_attach.go, pkg/cmd/dcos_cluster_remove.go, pkg/cmd/dcos_cluster_rename.go, pkg/config/config.go, pkg/config/manager.go, pkg/config/manager_test.go
- Implement `dcos cluster remove` 
- Implement `dcos cluster rename` 
- Implement `dcos cluster attach`
https://jira.mesosphere.com/browse/DCOS_OSS-1756
=> Implement some cluster commands

pkg/cmd/dcos_cluster_remove.go
This flags removes all configured clusters.
=> Accept an --all flags for `dcos cluster remove`

api/cli.go, cmd/dcos/main.go, design/cli.md, pkg/cli/context.go, pkg/cli/environment.go, pkg/cmd/dcos.go, pkg/cmd/dcos_auth_listproviders.go, pkg/cmd/dcos_cluster_list.go, pkg/cmd/dcos_cluster_remove.go, pkg/cmd/dcos_config_show.go, pkg/cmd/dcos_config_show_test.go
- Introduce a Context interface
- Add a test for `dcos config show`
=> Introduce a Context interface

Gopkg.lock, Gopkg.toml, api/cli.go, pkg/cli/context.go, pkg/cmd/auth/auth.go, pkg/cmd/auth/auth_login.go, pkg/login/flags.go, pkg/login/flow.go, pkg/login/login.go, pkg/login/provider.go, vendor/github.com/dgrijalva/jwt-go/.gitignore, vendor/github.com/dgrijalva/jwt-go/.travis.yml, vendor/github.com/dgrijalva/jwt-go/LICENSE, vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md, vendor/github.com/dgrijalva/jwt-go/README.md, vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md, vendor/github.com/dgrijalva/jwt-go/claims.go, vendor/github.com/dgrijalva/jwt-go/doc.go, vendor/github.com/dgrijalva/jwt-go/ecdsa.go, vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go, vendor/github.com/dgrijalva/jwt-go/errors.go, vendor/github.com/dgrijalva/jwt-go/hmac.go, vendor/github.com/dgrijalva/jwt-go/map_claims.go, vendor/github.com/dgrijalva/jwt-go/none.go, vendor/github.com/dgrijalva/jwt-go/parser.go, vendor/github.com/dgrijalva/jwt-go/rsa.go, vendor/github.com/dgrijalva/jwt-go/rsa_pss.go, vendor/github.com/dgrijalva/jwt-go/rsa_utils.go, vendor/github.com/dgrijalva/jwt-go/signing_method.go, vendor/github.com/dgrijalva/jwt-go/token.go
This implements the design page proposal at #1228
=> Implement `dcos auth login`

pkg/cli/context.go
Fix for https://jira.mesosphere.com/browse/DCOS-38016
=> Fixed race condition in Logger()

Gopkg.lock, Gopkg.toml, pkg/cli/context.go, pkg/cmd/dcos.go, pkg/config/cluster.go, pkg/plugin/manager.go, pkg/plugin/plugin.go, vendor/gopkg.in/yaml.v2/.travis.yml, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/NOTICE, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/go.mod, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go
Based on Brian's PR #1249, this adds Windows support and fixes regarding the architecture of the `plugin` package.
One thing we have noticed during the tests of this plugin system: the output of the logs on Windows is not the same as on macOS. This is due to Logrus and not our code thus we have not fixed the problem in this PR.
=> Added plugin system to DC/OS Go CLI.

api/cli.go, pkg/cli/context.go, pkg/clusterlinker/client.go, pkg/cmd/cluster/cluster.go, pkg/cmd/cluster/cluster_link.go, pkg/cmd/cluster/cluster_setup.go, pkg/cmd/cluster/cluster_unlink.go, pkg/config/manager.go, pkg/dcos/error.go, pkg/httpclient/client.go, pkg/login/login.go, pkg/setup/setup.go
Also added a helper function to allow names when choosing a cluster, `IsUniqueCluster(name string)`.
=> Added cluster link and unlink subcommands.

design/README.md, design/login.md
This document defines the goals and the high-level implementation of the CLI login flow.
=> Add a design page for CLI login

pkg/setup/flags.go, pkg/setup/setup.go
It allows to set a custom cluster name in the CLI configuration.
https://jira.mesosphere.com/browse/DCOS-18573
=> Add a `--name` flag to `dcos cluster setup`

pkg/cli/context.go
Otherwise the level which is set at startup is discarded.
It relies on a mutex to avoid races.
=> Always return the same logger from the Context

api/cli.go, pkg/cmd/dcos.go, pkg/cmd/dcos_test.go
This updates the main help message according to the design style guide.
https://jira.mesosphere.com/browse/DCOS_OSS-3705
=> Customize main dcos help message

pkg/cmd/auth/auth_listproviders.go, pkg/cmd/auth/auth_login.go, pkg/cmd/auth/auth_logout.go, pkg/cmd/cluster/cluster_attach.go, pkg/cmd/cluster/cluster_link.go, pkg/cmd/cluster/cluster_list.go, pkg/cmd/cluster/cluster_remove.go, pkg/cmd/cluster/cluster_rename.go, pkg/cmd/cluster/cluster_setup.go, pkg/cmd/cluster/cluster_unlink.go, pkg/cmd/config/config_set.go, pkg/cmd/config/config_show.go, pkg/cmd/config/config_unset.go
https://jira.mesosphere.com/browse/DCOS_OSS-3795
=> Added short help messages for all commands.

pkg/dcos/client.go
This was introduced in https://jira.mesosphere.com/browse/DCOS_OSS-2283.
https://jira.mesosphere.com/browse/DCOS_OSS-3808
=> Support the new dcos-variant field in /dcos-metadata/dcos-version.json

.appveyor.yml, pkg/login/flags_test.go, pkg/plugin/manager.go
This fixes Windows tests and adds an appveyor.yml file for CI integration.
https://jira.mesosphere.com/browse/DCOS_OSS-3952
=> Fix Windows tests

cmd/dcos/main.go, cmd/dcos/main_test.go, pkg/cmd/dcos.go
https://jira.mesosphere.com/browse/DCOS_OSS-3964
=>  Support --log-level and --debug flags

Dockerfile
https://github.com/golang/go/issues?q=milestone%3AGo1.10.3
=> Upgrade to Go 1.10.3

pkg/config/manager.go, pkg/config/manager_test.go, pkg/config/testdata/dcos_config_env/.dcos/dcos_env.toml, pkg/login/flags.go
- Update login flag descriptions
- Drop support for DCOS_CONFIG
=> Updates from doc review

ci/integration-tests.groovy, tests/integration/common.py, tests/launch_cluster.py
https://jira.mesosphere.com/browse/DCOS_OSS-3983
=> Auto-install core and enterprise plugins during integration tests

pkg/login/login.go, pkg/login/login_test.go, pkg/setup/setup.go
This adds a test for and addresses a couple cosmetic issues from https://github.com/dcos/dcos-cli/pull/1365
=> Add test and make small cosmetic changes to no auth fix

pkg/cmd/cluster/cluster_attach_test.go
This updates the test to use an absolute path when creating cluster
fixtures, otherwise they are missing the DCOS_DIR prefix and the test
fails.
=> Use an absolute path in TestClusterAttachBothConfiguredAndLinked

pkg/cmd/config/config_set.go, pkg/cmd/config/config_show_test.go, pkg/config/config.go, pkg/config/config_test.go
https://jira.mesosphere.com/browse/DCOS_OSS-4306
=>  Drop support for DCOS_URL and DCOS_ACS_TOKEN

pkg/cmd/auth/auth_listproviders_test.go, pkg/login/login.go, pkg/login/login_test.go
Fixes https://jira.mesosphere.com/browse/DCOS_OSS-4600
=> Added support for 'providers' endpoint in open-source clusters.

ci/index/html/artifacts.js
https://jira.mesosphere.com/browse/DCOS_OSS-4680
=> Fixed handling of "latest" links.

pkg/cmd/plugin/plugin_list.go
=> List commands of each plugin alphabetically.

Makefile
https://jira.mesosphere.com/browse/DCOS_OSS-5075
=> Bump dcos-core-cli to 1.13-patch.1

tests/integration/test_plugin.py
We've experienced flakiness with "Access is denied" errors on our Jenkins Windows nodes. This adds a retry loop for this case.
=> Add a workaround for Windows flakiness

README.md
New company name and website :)
=> Fix URL for CLI install in README

pkg/cmd/dcos.go, pkg/cmd/dcos_test.go, tests/integration/test_auth.py, tests/integration/test_cluster.py, tests/integration/test_config.py, tests/integration/test_help.py, tests/integration/test_plugin.py
What features does this change enable? What bugs does this change fix?
- [DCOS_OSS-5110](https://jira.mesosphere.com/browse/DCOS_OSS-5110)
=> Fix help menu to follow UX styleguide

CHANGELOG.md
Prepare changelog for the DC/OS CLI 1.0 release :tada: 
- https://jira.mesosphere.com/browse/DCOS-56863
=> Prepare changelog for 1.0

pkg/cmd/cluster/cluster_setup.go, pkg/cmd/completion/completion_data.gen.go, pkg/config/cluster.go, pkg/config/config.go, pkg/httpclient/client.go, pkg/setup/setup.go, tests/requirements.txt
By a mistake previous commit (f4361b13c82d257cc99c7ae6df9957ded950e6aa) introduced not formatted code. This commit is a follow up to format the code.
=> Fixes after bad merge

CHANGELOG.md, pkg/cmd/completion/completion.sh
This updates the completion script and changelog for the next 1.1.0 release.
=> Prepare 1.1.0 release

pkg/cli/global_flags_test.go, pkg/cmd/auth/auth_listproviders_test.go, pkg/config/manager_test.go, pkg/httpclient/client_test.go, pkg/log/formatter_test.go, pkg/login/flags_test.go, pkg/login/login_test.go, pkg/prompt/prompt_test.go
This naming is more common in Go.
=> Rename test fixtures to testCases

.golangci.toml, pkg/login/flow.go, pkg/login/flow_test.go, pkg/login/provider.go
This extracts some code from the login flow in dedicated functions and reduces the function complexity limit in .golangci.toml.
=> Reduce function complexity limit

design/release.md
Resolves https://jira.mesosphere.com/browse/DCOS-60814
=> Updated release.md to document using a new dev version.

ci/integration-tests-open.groovy, ci/integration-tests.groovy
Introduce authorization step to automatically notify maintainers on community contributions so that they can start approve and start CI.
=> chore(ci): introduce authorization step

CODEOWNERS
I've moved to other projects and will not be able to take on the responsibilities of a code owner, anymore. I'll be available for any questions, of course.
=> remove makkes from code owners

ci/integration-tests.groovy
Refs: https://github.com/dcos/dcos-core-cli/blame/5edeb7e8f5add1311c8f5c6d312c977e1e1de4f6/ci/build.groovy#L13-L21
=> Skip authorization on nightly build

ci/publish-artifacts.groovy
Refs: https://github.com/dcos/dcos-cli/commit/d94a01c3eb0626d18edbcd500f6b8f4649853e03#r41820808
See: https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-cluster-ops/job/mesosphere-dcos-cli/job/publish-index-artifacts/711/
=> Update S3 Jenkins secret
