dcos/dcos-cli

cli/tests/integrations/common.py

This is trivial, but some of the test output is so long, it's hard to get back up to the stack trace in my shell.  This truncates it.

truncated test output

---

cli/tests/integrations/test_marathon.py
dcos/marathon.py

Instead of leaving a stack trace, show more helpful message. 
```
Tamars-MacBook-Pro:dcos-cli tamar$ dcos marathon app update {"instances": 2}
Error: No JSON object could be decoded
```
In this command, app-id wasn't specified, and we parsed it as `"{"` with properties `'"instances": 2}'`, which is what caused the stacktrace.

dcos-1886 don't crash if invalid json commands

---

cli/dcoscli/node/main.py
cli/dcoscli/service/main.py
cli/dcoscli/task/main.py
cli/tests/data/service/marathon-user2.json
cli/tests/data/service/ssh_config
cli/tests/integrations/common.py
cli/tests/integrations/test_node.py
cli/tests/integrations/test_service.py
dcos/marathon.py
dcos/mesos.py
dcos/package.py
dcos/util.py

Follows the pattern of `dcos task log` and `dcos node log`
For marathon, uses ssh+journalctl
For non-marathon services, first we find the app running the service, then we find the task for that app, and print the logs for that task.

[DCOS-1133] dcos service log

---

dcos/http.py
dcos/util.py

The requests library already processes the http{s}_proxy and no_proxy
env variables, and using the `proxies` argument was overwriting, and
thus invalidating the no_proxy env variable.

accept no_proxy env variable

---

dcos/package.py

Since the errors get put into util.list_to_err which expects [str].

fix return type from [Error] to [str]

---

dcos/http.py

Through manual testing we nocited that the cli wasn't resolving proxy
setting during the first HTTP call in a session. This was because we
were using `session.send` method which doesn't do proxy resolution.
The higher-level methods: `session.request`, `session.get`, etc. do
proxy setting resolution.

Resolve HTTP proxy configuration on the first call

---

cli/dcoscli/package/main.py
cli/tests/integrations/test_package.py

--options=<missing.json>` to the beginning of stderr

[DCOS-610] Moved "missing options file" message for `dcos package install

---

cli/dcoscli/marathon/main.py
cli/tests/data/marathon/apps/cleaned_response.json
cli/tests/data/marathon/apps/response.json
cli/tests/unit/test_marathon_validation.py

Since we are using the resource definition from marathon, it contains fields that should not be specified by users which need to be removed before validating the update.

dcos-2471 allow marathon app updates during a deployment

---

cli/tests/integrations/common.py
cli/tests/integrations/test_package.py

Sometimes `dcos service --inactive` returns other services created by other tests. E.g. `marathon-user`, etc.

Fix package install test

---

cli/dcoscli/marathon/main.py
cli/tests/integrations/test_marathon.py

(This is mostly splitting hairs)
App id was missing from the example text. Also we were using "E.g." in one place "Usage" in other

Add appId to example and made the two texts consistent ('E.g.' v/s 'Usage')

---

cli/tests/integrations/test_service.py

Since it added 40min to the test run time.

Revert "Enable shutdown test"

---

README.rst
cli/tox.ini
cli/tox.win.ini
tox.ini
tox.win.ini

We are not using the environment variable during the tests. Let's remove
all reference to it.

Remove EXHIBITOR_URL environment variable

---

dcos/subcommand.py
dcos/util.py

On Windows `NamedTemporaryFile` does not lend itself to be opened the second time when it is already open. Source : https://docs.python.org/2/library/tempfile.html
> 
Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later). 
Also closing the file would delete it by default. So to open the file second time on windows(and also not break on Unix like systems) the workaround is to set `delete=False` while creating the file, closing it after use and then manually deleting it after done.  
Without this fix you would see errors like : 
`
2016-02-09 16:09:02,290 c:\users\surdy\downloads\dcos\lib\site-package\dcos\subcommand.py:_execute_install:411 - Install …

Make NamedTemporaryFile play nice on Windows

---

cli/dcoscli/service/main.py

The ssh user for `dcos service` is hardcoded as `core` [here](https://github.com/mesosphere/dcos-cli/blob/5cf9ef0f1f14e63b5c6d0642ab380c7f8a08fc62/cli/dcoscli/service/main.py#L274). If you are a DCOS community edition user this works great. 
But if you are an Enterprise Edition customer you might not be on CoreOS. So you would want to use your own ssh_config for the hosts using `dcos service ----ssh-config-file`. Even if you have a `User` specified in the config file it won't be used since the hardcoded `core@` would take precedence over `User` in config file.  
There is no way to override,using a config, what's hardcoded the command line and I also understand to urge to keep  `core@` as default. So I have tweaked the code such that it does not use `core@` if you have a …

Don't use core as the user when an ssh config is provided

---

cli/dcoscli/package/main.py

We need to have _main always return all available commands to show the
user

check for cosmos in each `package` subcommand call

---

dcos/cosmospackage.py
dcos/http.py

/capabilites endpoint doesn't return url credentials in response, so use
request url. Also raise DCOSException, so we get `Authentication failed`
error message.

fix username/password for capabilities endpoint

---

cli/dcoscli/package/main.py

Currently `dcos package install --options=~/path/to/options.json` or `dcos package install --options=~surdy/path/to/options.json` fails silently as it cannot process `~`. 
I have used `os.path.expanduser`to get around this problem

Enable --options to interpret ~ in the path

---

cli/dcoscli/main.py
dcos/cosmospackage.py
dcos/errors.py
dcos/http.py

We try to get the CLUSTER_ID before we run the user specified command.
If the user if authenticated, but not authorized (to get the
CLUSTER_ID), let them continue and error based on access to the command
they ran.

error based on user command auth not auth to get CLUSTER_ID

---

dcos/cosmospackage.py

`JsonSchemaMismatch` is returned for all vaildation errors. We we're only handling bad types, not additional properties. Add the later, and don't require fields to be present in returned error message. New error message for additional properties: 
```
cli (issue-#498)$ dcos package install --yes kafka --options=tmp123.json
This will install Apache Kafka DCOS Service.
Error: Options JSON failed validation
Unexpected properties: ['broker-count', 'placement-strategy', 'plan-strategy', 'pv']
Path: kafka
Please create a JSON file with the appropriate options, and pass the /path/to/file as an --options argument.
```

allow flexibility in error messaging for JsonSchemaMismatch error type

---

cli/dcoscli/package/main.py
cli/dcoscli/tables.py
cli/tests/integrations/test_package.py
cli/tests/unit/test_tables.py
dcos/cosmospackage.py

removed superfluous outer list of packages 
```json
{
"packages": [
{
"currentVersion": "0.2.0-1",
"description": "Apache Cassandra running on Apache Mesos",
"framework": true,
"name": "cassandra",
"tags": [
"data",
"database",
"nosql"
],
"versions": {
"0.2.0-1": "0"
}
}
]
}
```

clean up `dcos package search --json` response

---

cli/dcoscli/analytics.py
cli/tests/unit/test_analytics.py

If no command specified args has command key, but it equals None

Segment bugfix

---

ccm/tests_ccm_cluster.sh
cli/tests/data/analytics/dcos_no_reporting.toml
cli/tests/data/analytics/dcos_reporting.toml
cli/tests/data/analytics/dcos_reporting_with_url.toml
cli/tests/data/auth/dcos_with_credentials.toml
cli/tests/data/auth/dcos_without_credentials.toml
cli/tests/data/config/missing_params_dcos.toml
cli/tests/data/marathon/missing_marathon_params.toml
cli/tests/data/ssl/ssl.toml
cli/tests/integrations/common.py
cli/tests/integrations/test_auth.py
cli/tests/integrations/test_config.py
cli/tests/integrations/test_marathon.py
cli/tests/integrations/test_ssl.py
cli/tests/unit/test_http_auth.py

Instead of using different toml files in tests, just alter the config value for that test. This makes the tests more manageable especially since we now need to add auth credentials in the toml file.

clean up toml test files

---

cli/tests/data/package/json/test_describe_app_options.json
cli/tests/data/package/json/test_describe_marathon_app_render.json
cli/tests/integrations/common.py
cli/tests/integrations/test_node.py
cli/tests/integrations/test_package.py
cli/tests/integrations/test_service.py
cli/tests/integrations/test_task.py
dcos/cosmospackage.py

We shouldn't fail when mesos adds new properties, instead verify
specific properties

be less strict in mesos schema checks

---

cli/dcoscli/tables.py
cli/tests/unit/data/package_search.txt

PrettyTable renders each row to be the width of the largest row.
Packages with long descriptions make the table very hard to read.

limit length of description in search table

---

EXTERNAL_LICENSES.md

Generated with `yolk -l -f License > EXTERNAL_LICENSES.md` in the dcos-cli/cli virtualenv environment.
Manually changed setuptools to MIT.

External license

---

cli/dcoscli/package/main.py
dcos/cosmospackage.py

With universe updates to change where the cli is defined, we now first
look for the cli definition in resource.cli, and if not found, look for
command.json in the package definition.

update `package describe --cli` to look at command + resource json

---

cli/setup.py

Version 1.3.0 of the package was just release and it breaks the CLI

Pin the pkginfo package to 1.2.1

---

cli/dcoscli/data/help/task.txt
cli/dcoscli/task/main.py
cli/tests/data/help/task.txt
cli/tests/data/marathon/apps/sleep-completed1.json
cli/tests/integrations/test_task.py
dcos/mesos.py

As per documentation `dcos task --completed` was intended to show BOTH completed and running tasks. In practice it only shows completed tasks.

Make --completed great again

---

cli/dcoscli/node/main.py

If I try to skip HostKeyChecking while sshing into a DC/OS node it only works if I'm not using `--master-proxy`
```
dcos node ssh  --option="StrictHostKeyChecking=no" --leader --master-proxy
Running `ssh -A -t -o StrictHostKeyChecking=no core@52.38.226.230 ssh -A -t core@10.0.7.49`
The authenticity of host '10.0.7.49 (10.0.7.49)' can't be established.
ED25519 key fingerprint is 53:5b:89:66:bb:f7:aa:7e:60:39:87:4b:5c:33:42:e0.
Are you sure you want to continue connecting (yes/no)? 
```
Currently `dcos node ssh  --option="StrictHostKeyChecking=no" --leader --master-proxy--option="StrictHostKeyChecking=no"` gets interpreted as `ssh -A -t -o StrictHostKeyChecking=no core@52.38.226.230 ssh -A -t core@10.0.7.49` with this change it will be interpreted as `ssh -A -t -o StrictHostKeyChecking=no …

Apply --option to connection from master-proxy as well

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/node/main.py
cli/tests/data/help/node.txt
cli/tests/integrations/test_node.py

Because `echo <command> | dcos node ssh ` felt hacky and did not work so well for me

Enable dcos node ssh to run a command

---

cli/tests/unit/test_task.py
cli/tox.ini
cli/tox.win.ini
dcos/mesos.py
tox.ini
tox.win.ini

Instead of crashing, if looking for a task by a fltr, if a task is an
exact match, return that task.

handle mesos tasks having ids that are substrings of each other

---

cli/tests/integrations/test_node.py

DC/OS bumped the coreOS version, and just using PasswordAuthentication
is now no longer enough to turn off interactive mode. BatchMode covers
all types of authentication.

use BatchMode instead of PasswordAuthentication for ssh

---

cli/dcoscli/subcommand.py
dcos/subcommand.py

With this change, we need to specify the imports in pyinstaller spec
file, so leave as is.

revert "remove code duplication (#648)"

---

dcos/cosmospackage.py
dcos/errors.py
dcos/http.py

default requests to cosmos to version 2, with a version 1 fallback

---

cli/tests/integrations/test_marathon.py
dcos/marathon.py

We were using it to make sure we have a recent version of Marathon. Since
DC/OS CLI 0.4.0+ is only compatible with DC/OS 1.6.1, the Marathon
check is no longer necessary. It is also messing with ACLs since
v2/apps is at a user level and v2/info is an admin level.

remove v2/info call from Marathon client

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/node/main.py
cli/tests/data/help/node.txt
cli/tests/unit/test_node.py

a new command to manage a set of cluster logs would be:
dcos node diagnostics ...
a zip file with collected logs is now called a `diagnostics bundle`

rename snapshot command

---

dcos/config.py

We shouldn't have the binary need to call itself, especially for information it already has.

use config-schema datafiles for default commands

---

ccm/wait_for_ccm_cluster.sh

This will allow dcos-cli tests not to fail until the [CCM fix](https://github.com/mesosphere/cloud-cluster-manager/pull/136) can be deployed.

Wait for `cluster_info` JSON field to be populated

---

cli/tests/integrations/common.py
cli/tests/integrations/test_package.py

* Add a function name base64_to_dict that converts a base64 string into
a python dictionary
* Change the base64 string comparisons in test_package.py to comparisons
in their python dictinary form. This will make error messages more
descriptive

fix issue 666

---

cli/dcoscli/package/main.py
cli/tests/data/package/json/test_describe_marathon.json

We were adding in all versions of a package, but this doesn't make sense
since different versions have different package.json contents. A user
can still see all versions of a package with `--package-versions` flag.

change `package describe` to output package.json without modification

---

cli/dcoscli/data/help/task.txt
cli/dcoscli/task/main.py
cli/tests/data/help/task.txt
cli/tests/integrations/test_task.py

If no arguments were given for`dcos task log` and `dcos task ls`, we
were processing the command as `dcos task` with task-id log|ls.

fix docopt resolution order in `dcos task`

---

dcos/http.py

We should take the username typed by the user as is. No need to lower
the case of the string.

Don't change the case of the username

---

dcos/subcommand.py

Follows up on 1f7d77ec
Before:
```
$ dcos spark -h
Traceback (most recent call last):
File "/home/nick/code/dcos-cli/cli/env/bin/dcos", line 9, in <module>
load_entry_point('dcoscli===SNAPSHOT', 'console_scripts', 'dcos')()
File "/home/nick/code/dcos-cli/cli/dcoscli/main.py", line 19, in main
return _main()
File "/home/nick/code/dcos-cli/cli/dcoscli/main.py", line 86, in _main
exitcode, _ = sc.run_and_capture()
File "/home/nick/code/dcos-cli/dcos/subcommand.py", line 681, in run_and_capture
subproc = subprocess.Subproc().Popen(
AttributeError: 'module' object has no attribute 'Subproc'
```
After:
```
$ dcos spark -h
Usage:
[...]
```

Fix command execution

---

cli/tests/data/config/invalid_section.toml
cli/tests/integrations/test_config.py
dcos/config.py

For example, if you have a spark section in the config, and you uninstall the spark subcommand, trying to add anything to the config will result in a 'spark is not a dcos command' error. 
Instead, if the user is not changing the 'spark' section in the toml, we shouldn't be validating it.

when adding new config value, only check that section of config

---

cli/binary/binary.spec
cli/dcoscli/data/help/marathon.txt
cli/dcoscli/marathon/main.py
cli/dcoscli/subcommand.py
cli/tests/data/help/marathon.txt
cli/tests/integrations/test_marathon.py
cli/tests/integrations/test_marathon_pod.py
cli/tests/unit/test_marathon_pod.py
dcos/data/marathon/error.schema.json
dcos/jsonitem.py
dcos/marathon.py
setup.py
tests/test_marathon.py
tox.ini

Did some refactoring to support unit tests of Marathon interfaces. This especially helped for tests of error responses.
This PR is mostly infrastructure. The remaining pod subcommands will take much less time to implement with this foundation.

Implement `pod add` subcommand

---

cli/dcoscli/marathon/main.py
cli/tests/integrations/test_marathon_pod.py
cli/tests/unit/test_marathon_pod.py
dcos/marathon.py
tests/test_marathon.py

The integration tests for `pod update` against the `feature/pods` branch of Marathon still fail, because there's a discrepancy between what the RAML spec says vs. what the endpoint returns in the response. I'm assuming we can address that during the end-to-end test phase.

Implement `pod update`

---

cli/dcoscli/data/help/node.txt
cli/tests/data/help/node.txt

The keyword usage was misleading before.

Improved help for dcos node diagnostics create.

---

cli/dcoscli/marathon/main.py
cli/tests/unit/test_marathon_pod.py
dcos/marathon.py
tests/test_marathon.py

Fixes #759.
~~**MERGE #768 BEFORE REVIEWING**~~
This PR updates all `dcos marathon pod` subcommands to check if the Marathon instance supports the pods HTTP API. This is accomplished by making a `HEAD /v2/pods` request and checking if the response's status code is in the 2xx range. If the status code is 404, we know pods are not supported. And if the status code is anything else, we default to the existing error handling for HTTP requests to Marathon.
The console output when a command is not supported is as follows:
```
$ dcos marathon pod list
This command is not supported by Marathon
```

All pod subcommands check for Marathon support

---

cli/tests/integrations/test_marathon.py
dcos/marathon.py
tests/test_marathon.py

- State that changes cannot be made
- Refer to an existing deployment as the reason

Make Marathon 409 response status error message less confusing

---

cli/dcoscli/data/help/marathon.txt
cli/dcoscli/marathon/main.py
cli/tests/data/help/marathon.txt
cli/tests/integrations/test_marathon_pod.py
cli/tests/unit/test_marathon_pod.py

Pod descriptor JSONs have too many important nested fields, making
command-line properties awkward to specify. Removal improves the
user experience of the command.
Fixes #779.

Remove `<properties>` arguments from `marathon pod update`

---

cli/tests/integrations/test_marathon.py
cli/tests/integrations/test_marathon_pod.py
cli/tox.ini

Add PODS_ENABLED to Tox env var whitelist
You'll be happy/relieved to know that all tests still pass! I also updated #783 so that we remember to undo this change as well.

Fix accidental skipping of pods integration tests in CI builds

---

cli/dcoscli/tables.py
cli/tests/data/marathon/pods/double.json
cli/tests/data/marathon/pods/doubleplusgood.json
cli/tests/data/marathon/pods/good.json
cli/tests/fixtures/marathon.py
cli/tests/integrations/test_marathon_pod.py
cli/tests/unit/data/pod.txt
cli/tests/unit/data/pod_without_instances.txt
cli/tests/unit/data/pod_without_spec_version.txt
cli/tests/unit/test_marathon_pod.py
cli/tests/unit/test_tables.py
dcos/marathon.py
tests/test_marathon.py

New information in table view:
- container names
- instance count
- creation timestamp (version)
- status
- last status change timestamp (status since)
See `cli/tests/unit/data/pod.txt` in this PR for example table output.

Update `marathon pod list` to use `GET /v2/pods/::status`

---

cli/dcoscli/config/main.py
cli/tests/integrations/test_config.py

#683 
`dcos config show` now has spaces between `key` and `value` instead of `=`

make `dcos config show` consistent with other `dcos config` commands

---

cli/tests/integrations/common.py
cli/tests/integrations/test_package.py
cli/tests/integrations/test_service.py
cli/tests/integrations/test_task.py
dcos/marathon.py
tests/test_marathon.py

Pod tests for PR #806 won't pass until this is merged.

Marathon endpoint for `pod kill` now ends with plural `::instances`

---

cli/tox.ini
cli/tox.win.ini
tox.ini
tox.win.ini

bug introduced is `0.10` from here: https://github.com/PyCQA/flake8-import-order/commit/863f4597ab4e0879ee6058fab3f5e5b1df1f3463

tox: pin flake8-import-order due to import bug

---

bin/install/install-dcos-cli.sh
bin/install/install-optout-dcos-cli.sh
cli/setup.cfg
setup.cfg

We want to be able to use python3 features.
For users on DC/OS 1.8+: They should be using the binary CLI- so this should not affect them
For legacy users (DC/OS < 1.8): With this change, they will download the latest supported 2.7 version when following the UI instructions from their cluster.  
For developers: python3 wheels for `dcos` and `dcoscli` packages will be published. If they want to use python2.7 they can still use the older 2.7 published wheels for this package.

python27: stop publishing wheel

---

cli/dcoscli/auth/main.py
cli/tests/unit/test_http_auth.py
dcos/errors.py
dcos/http.py

We were retrying requests with 401 so that we can use the response
headers to determine type of authentication. Instead, always send
request with auth if we already have credentials (from
core.dcos_acs_token).
This also fixes multi-part requests that currently break if we have to
retry the request (since the stream gets opened by the initial request).

http: don't retry requests if response is 401

---

cli/dcoscli/main.py
dcos/subcommand.py

In particular https://github.com/PyCQA/pycodestyle/pull/536 which landed as part
of 2.1.0 today (https://github.com/PyCQA/pycodestyle/blob/2.2.0/CHANGES.txt#L15)
finds one place where there should have been another newline.

Update for recent pycodestyle changes

---

tests/test_marathon.py

Replace an actual Response object with a mock to
ensure we have the correct state for the test

Fix failing test caused by requests library update

---

cli/dcoscli/tables.py
cli/dcoscli/util.py
dcos/config.py
dcos/marathon.py
dcos/subcommand.py
setup.py

Builtin, third party, and first party are all supposed to have a newline between
them. Most of the codebase was doing this, but some had snuck through. This
updates those ones to follow the coding style. These are caught by recent
changes in the code style checking plugin making it more strict / accurate.

Add some missing newlines between import sections

---

cli/dcoscli/job/main.py
cli/tests/data/metronome/jobs/sch-no-array.json

allowing the schedule json to be in array or non array format.  still only allows 1 but allows flexability.  it also provides better error reporting

allow single entry schedule in json

---

ccm/start_ccm_cluster.sh

This makes the clusters line up with developer expectations

Add a public agent to CI test clusters

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/log.py
cli/dcoscli/node/main.py
cli/dcoscli/service/main.py
cli/dcoscli/task/main.py
cli/setup.py
cli/tests/data/help/node.txt
cli/tests/integrations/common.py
cli/tests/integrations/test_node.py
cli/tests/integrations/test_service.py
cli/tests/integrations/test_task.py
cli/tests/unit/test_node.py
cli/tests/unit/test_task.py
dcos/sse.py
setup.py

with 1.9 release all system and container logs will go to sd journal on each
host. This PR adds dcos-log support to CLI.
before using newest API CLI will try to get the cosmos capability "LOGGING".
If the cluster supports dcos-log, it will use it. If the requests fails or
dcos-log missing LOGGING capability, we will default to mesos files API.
Relevant PRs:
dcos/dcos#971
dcos/dcos#832
dcos/cosmos#527

switch to `dcos-log` logging backend

---

cli/dcoscli/task/main.py

if executor was unable to start, no logs are avaiable.

dcos task log: improve user error message

---

dcos/http.py
dcos/packagemanager.py

- add raise DCOSAuthenticationException in dcos.http.request if token is
invalid.
- raise DCOSAuthenticationException in
dcos.packagemanager.PackageManager().has_capability if user is not logged in

dcos/http: raise exception if expired token

---

cli/dcoscli/tables.py

In the scenario having an app definition like with a real long `cmd` section, the command `dcos marathon app list` would be jumbled. Therefore it would be nice to have the possibility to truncate the cmd section.
Before the change:
```
dcos marathon app list
ID      MEM   CPUS  TASKS  HEALTH  DEPLOYMENT  WAITING  CONTAINER  CMD                                                                                                                                                                   
/sleep  128  0.001   1/1    ---       ---      False      mesos    sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000 && sleep 1000  
```
After the change:
```
dcos marathon app list
ID      MEM   CPUS …
```

Added possibility to truncate a table cell

---

cli/dcoscli/data/help/job.txt
cli/tests/data/help/job.txt

Fixed typo in dcos job kill help.

Fixed typo in help for dcos job kill

---

dcos/util.py

I spent a while this morning trying to figure out why read-only permissions on my ssh key were "too open" :)

Allow read-only permissions on ssh key

---

dcos/packagemanager.py

Better error message.
Before:
```
Error: Options JSON failed validation
Found: 128
Path: service.mem
Please create a JSON file with the appropriate options, and pass the /path/to/file as an --options argument.
```
Seeing this, I might think that it thinks the value is missing but I check my config and it's there so I would be puzzled about what the problem is.
After:
```
Found: 128
Required minimum: 256
Path: service.mem
Please create a JSON file with the appropriate options, and pass the /path/to/file as an --options argument.
```
This makes it clear what the actual problem is.
Cc: @matthewdfuller

Improve error message for not meeting minimum

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/node/main.py
cli/tests/integrations/test_node.py

In our DC/OS setup, the master node doesn't have a public IP and we use a public jump box to get to all nodes in the cluster. This adds a `--proxy-ip` option to `dcos node ssh`, so that we can specify which box to use as the SSH proxy.
In our DC/OS setup, the master node doesn't have a public IP and we use a public jump box to get to all nodes in the cluster. This adds a `--proxy-ip` option to `dcos node ssh`, so that we can specify which box to use as the SSH proxy.
```
$ dcos node ssh --proxy-ip $DCOS_PROXY_IP --mesos-id=74df965e-a46e-46a9-8d2a-639db0af0e25-S2
Running `ssh -A -t core@<redacted> ssh -A -t core@10.10.12.29 `
Last login: Fri Feb 10 23:07:26 UTC 2017 from 10.10.3.201 on pts/0
CoreOS stable (1185.5.0)
Update Strategy: No Reboots
Failed Units: 1
user@0.service …
```

dcos node ssh --proxy-ip=<proxy-ip>

---

dcos/packagemanager.py

Before:
```
Error: Options JSON failed validation
Path: environment
```
After:
```
Error: Options JSON failed validation
Required parameter missing: dbHost
Path: environment
```
Fixes: https://dcosjira.atlassian.net/browse/DCOS-191
Cc: @tamarrow, @jerith, @matthewdfuller

Better error when package config var missing

---

tests/test_packagemanager.py

I noticed that `dcos.packagemanager` had 0% test coverage. So I wrote some tests. If you like, I can write some more.
Before:
```
$ tox -e py35-unit | grep 'packagemanager.*%'
.tox/py35-unit/lib/python3.5/site-packages/dcos/packagemanager.py     252    252     0%
```
After:
```
$ tox -e py35-unit | grep 'packagemanager.*%'
.tox/py35-unit/lib/python3.5/site-packages/dcos/packagemanager.py     252    139    45%
```
Cc: @matthewdfuller

Add tests for dcos.packagemanager

---

README.rst
cli/tests/integrations/test_ssl.py
dcos/data/config-schema/core.json

The docs say we need 3.4, but then make tells me 3.5.
One of these is wrong.
```
 ~/src/m8e/dcos-cli [master|…1]
14:59 $ make env
bin/env.sh
Cannot find supported python version 3.5. Exiting...
make: *** [env] Error 1
```

fix python version requirement

---

cli/dcoscli/node/main.py
cli/tests/unit/test_node.py

currently the command
dcos node log --leader will not get logs from mesos leader node. It will make
a request against `dcos_url` variable. We should redirect the request to a
leading mesos node unless --component dcos-marathon is used. In this case
we have to redirect the request to a leading marathon master (which can be
a totally different node)

fix --leader flag for dcos-log

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/node/main.py
cli/tests/integrations/test_node.py

People working on the soak clusters at Mesosphere receive alerts when
something unexpected is happening, e.g. 'Some containers failed to
launch on an agent on agent:<private_ip>'.
This new command allows us to quickly take a look without
having to check the Mesos UI to find the Mesos ID of an agent. Another
use case is when a developer sees an unhealthy AWS instance that is a
DC/OS private agent without a public IP.

dcos node ssh --private-ip=<private-ip>

---

cli/dcoscli/log.py
cli/dcoscli/node/main.py
cli/dcoscli/service/main.py
cli/dcoscli/task/main.py
cli/tests/integrations/test_node.py
cli/tests/integrations/test_task.py

DC/OS metadata endpoint will expose a config where the user is able to specify
what logging strategy to use. We should be using `dcos-log` API only if user
explicitly disables sandbox logging.
https://github.com/dcos/dcos/pull/1259

use config file to determine logs source

---

dcos/mesos.py

Previously, we weren't passing the recursive definition of a containerID all the way through the call chain. This prohibited us from running `dcos task exec` inside nested containers. This simple fix now allows this.

Fixed bug to allow 'dcos task exec' to work with pods.

---

cli/dcoscli/tables.py
cli/tests/unit/data/task.txt

This makes it easy to see a task, and ssh into the agent using either the private ip or the mesos id.

task: add mesos agent ID to `dcos task` table

---

.gitignore

I think these `.cache` directories are coming from newer versions of `py.test`, which [cache info about test runs](http://doc.pytest.org/en/latest/cache.html).
```
$ git status
On branch master
Your branch is up-to-date with 'upstream/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.cache/
cli/.cache/
```

.gitignore: Add .cache

---

cli/tests/integrations/test_node.py

dcos/dcos-metrics#77 changed the key for system uptime in the node
metrics data endpoint from `uptime` to `system.uptime`. This had
the side-effect of breaking the CLI integration tests.
Functionality was not affected, but I'll be careful to avoid this in the 
future. Apologies for all the inconvenience caused.

Update test to reflect metrics interface change

---

dcos/util.py

because for symlinks we should look at the permissions of the file
itself rather than the permissions of the symlink.
To illustrate why, look at the following example in which I make the
symlink read-only to make `dcos` happy, but in fact this is not very
secure, because the symlink is pointing to a world-readable and writable
file.
Before:
```
$ ls -l ~/.dcos/dcos.toml ~/dcos-aws-sandbox.toml
lrwxr-xr-x  1 abramowi  staff   37 Mar 14 08:28 /Users/abramowi/.dcos/dcos.toml@ -> /Users/abramowi/dcos-aws-sandbox.toml
-rwxrwxrwx  1 abramowi  staff  542 Mar 14 08:27 /Users/abramowi/dcos-aws-sandbox.toml*
$ dcos node
Permissions '0o755' for configuration file '/Users/abramowi/.dcos/dcos.toml' are too open. File must only be accessible by owner. Aborting...
$ chmod -h 600 ~/.dcos/dcos.toml
$ ls …
```

Use stat (not lstat) to check file permissions

---

cli/dcoscli/log.py
cli/dcoscli/node/main.py

journald task logging is disabled by default in 1.9GA, however, we
still want to be able to read journald (system) logs with command
`dcos node log ...`

enable dcos-log for system logs

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/node/main.py
cli/dcoscli/tables.py
cli/tests/integrations/test_node.py

This lets the user control what fields are printed in the table and allows printing arbitary data that wasn't possible to show before, except when using `--json`.
Here's an example of referencing a custom attribute called `ethos_role`:
```
$ dcos node --field=ip --field=id --field=attributes.ethos_role
IP                          ID                    ATTRIBUTES.ETHOS_ROLE
10.10.3.201   74df965e-a46e-46a9-8d2a-639db0af0e25-S3          public
10.10.12.29   74df965e-a46e-46a9-8d2a-639db0af0e25-S2         control
10.10.12.174  74df965e-a46e-46a9-8d2a-639db0af0e25-S0          worker
10.10.12.237  74df965e-a46e-46a9-8d2a-639db0af0e25-S1          proxy
```
By using a `:` in a field name, you can give it a custom heading in the table.
```
$ dcos node --field=ip --field=id …
```

dcos node: Add --field option

---

cli/setup.py
setup.py

because `jwt` is used only in `dcos/auth.py`
In fact, it looks like it's only used in `dcos/auth.py` and not used at all in `dcos/cli`:
```
$ ag --ignore=tests --ignore=env --ignore=venv jwt --ignore='*.egg-info'
cli/setup.py
69:        'PyJWT==1.4.2',
dcos/auth.py
7:import jwt
21:       'acsjwt' (DC/OS acs auth), 'oauthjwt' (DC/OS acs oauth), or
33:                       if auth_type.rstrip().lower().startswith("acsjwt") or
34:                       auth_type.rstrip().lower().startswith("oauthjwt")),
42:                   "'{}', DC/OS only supports ['oauthjwt', 'acsjwt']".format(
89:    jwt token encoded with private key).
257:        'token': jwt.encode(
323:            if auth_scheme == "oauthjwt":
325:            # auth_scheme == "acsjwt"
```
so I think the dependency should be moved.

Move PyJWT dep from cli/setup.py to setup.py

---

README.rst
cli/bin/test.sh
cli/tests/data/config/invalid_section.toml
cli/tests/data/config/parse_error.toml
cli/tests/integrations/test_auth.py
cli/tests/integrations/test_config.py
cli/tests/integrations/test_job.py
cli/tests/integrations/test_marathon.py
cli/tests/integrations/test_package.py
cli/tests/integrations/test_ssl.py

Now that clusters are managed by the CLI we should use it instead of
relying on using DCOS_CONFIG to point to the correct config.

tests: don't use DCOS_CONFIG

---

dcos/subcommand.py

For a given cluster, read in subcommand from that cluster specific
directory + global directory of subcommands. If a subcommand with the
same name exists in both, use the subcommand in the cluster specific
directory.

subcommand: install subcommands in cluster specific directory

---

cli/dcoscli/config/main.py
cli/tests/integrations/test_config.py

so we know what the active config file is:
```
$ dcos config validate
Validating /Users/abramowi/.dcos/dcos.toml ...
Congratulations, your configuration is valid!
$ dcos config validate
Validating /Users/abramowi/.dcos/dcos.toml ...
Error: Additional properties are not allowed ('prompt_login' was unexpected)
Path: core
Value: {"prompt_login": true, ...}
```

Show path of config file we're validating

---

cli/dcoscli/data/help/job.txt
cli/dcoscli/job/main.py

Refactoring in https://github.com/dcos/dcos-cli/pull/826 introduced wrapper classes for metronome, but broke functionality to kill a currently running job. This issue was described in https://jira.mesosphere.com/browse/DCOS-14685.
The problematic lines are 229 to 231 in this diff: https://github.com/dcos/dcos-cli/pull/826/files#diff-7779ca4ca7c5274182e7ca22c94ff4e2L229. You see that `dead` iterator variable was used and that `response` was assigned before the PR was merged.
By the way I fixed the broken functionality to kill a job run directly through providing run-id. For example via `dcos job kill longsleep 20170322093250yxIvK`.
Walk through with one running job, two running jobs and dedicated kill of a particular job looks like:
```
Johanness-MacBook-Pro:cli junterstein$ dcos job kill …
```

Fixes DCOS-14685: CLI was not able to kill a running metronome job

---

cli/dcoscli/data/help/package.txt
cli/dcoscli/package/main.py
cli/tests/integrations/test_package.py

e.g.:
```
$ dcos package repo list
ethos-core-universe: https://dcos-private-universe.s3.amazonaws.com/ethos/1.0/unstable/repo/repo-up-to-1.8.json
Universe: https://universe.mesosphere.com/repo
$ dcos package repo remove 'ethos-core-universe' 'Universe'
$ dcos package repo list
There are currently no repos configured. Please use `dcos package repo add` to add a repo
```

Allow removing multiple repos in one command

---

cli/dcoscli/tables.py
cli/tests/integrations/test_node.py

like `TASK_RUNNING` for example.
```
$ dcos node --field=TASK_RUNNING
HOSTNAME         IP                          ID                    TASK_RUNNING
10.10.12.174  10.10.12.174  74df965e-a46e-46a9-8d2a-639db0af0e25-S0       11
10.10.12.183  10.10.12.183  74df965e-a46e-46a9-8d2a-639db0af0e25-S4       6
10.10.12.29   10.10.12.29   74df965e-a46e-46a9-8d2a-639db0af0e25-S2       8
10.10.3.201   10.10.3.201   74df965e-a46e-46a9-8d2a-639db0af0e25-S3       0
```

node: Allow showing non-lowercase fields

---

cli/dcoscli/config/main.py
cli/tests/integrations/test_config.py
dcos/config.py

To setup a cluster, we should now be using `dcos cluster setup
<dcos_url>` and not have to mess with the config properties.

config: add deprecation notice for `dcos config set core.dcos_url`

---

cli/dcoscli/data/help/package.txt
cli/dcoscli/package/main.py
cli/tests/integrations/test_package.py
dcos/subcommand.py

This allows you to install a CLI subcommand for all your clusters (ie
globally) or just for the attached cluster.

package: add --global option for CLIs in `package install`

---

cli/dcoscli/data/help/marathon.txt
cli/dcoscli/marathon/main.py
cli/tests/integrations/test_marathon.py
dcos/marathon.py

- Using `v2/tasks/delete` marathon endpoint
- Possible to kill multiple tasks at once
- Setting `scale=True` will scale down the corresponding app

Add `dcos marathon task kill` command

---

cli/dcoscli/data/help/job.txt
cli/dcoscli/job/main.py
cli/tests/integrations/test_job.py
dcos/metronome.py

updated tests to support.
output is either:
```
$ dcos job run pikachu
Run ID: 20170419234147iDjEo
```
or
```
$ dcos job run pikachu --json
{
"completedAt": null,
"createdAt": "2017-04-19T23:42:14.097+0000",
"id": "20170419234214aphte",
"jobId": "pikachu",
"status": "INITIAL",
"tasks": []
}
```

updating run job to return the run id.  

---

cli/dcoscli/cluster/main.py
cli/dcoscli/config/main.py
cli/dcoscli/data/help/cluster.txt
cli/dcoscli/tables.py
cli/tests/integrations/test_config.py
cli/tests/integrations/test_job.py
cli/tests/integrations/test_marathon.py
cli/tests/integrations/test_package.py
cli/tests/integrations/test_ssl.py
dcos/cluster.py
dcos/http.py

* open DC/OS clusters don't have a cluster cert, default to insecure requests
* add --attached param to `cluster list`
* improve error messages
* use current config for http._verify_ssl

cluster: ux improvements

---

dcos/subcommand.py

I got this error and wanted to know what executables, it had found.
e.g.:
```
$ dcos fd image list
Found more than one executable for command 'fd'. ['/Users/abramowi/.dcos/subcommands/fd/env/bin/dcos-fd', '/Users/abramowi/.dcos/subcommands/flight-director/env/bin/dcos-fd']
```

More info when > 1 executable subcommand

---

DESCRIPTION.rst

I wonder if this is the reason that the description is not rendering properly on PyPI...?
https://pypi.python.org/pypi/dcos

DESCRIPTION.RST: Extend underline

---

cli/dcoscli/task/main.py
cli/tests/integrations/test_task.py
cli/tests/unit/test_task.py
dcos/mesos.py

This commit:
https://github.com/dcos/dcos-cli/commit/8971ccdb081f5b902387d72185fadb2cc6ed1fbd
Inadvertently undid changes originally introduced in this commit:
https://github.com/dcos/dcos-cli/commit/f33a45ee94377e2b4654d9d69812320e4b2b823b
Unfortunately, the integration tests didn't catch this because all
`task exec` integration tests were hidden behind an environment variable:
@pytest.mark.skipif('DCOS_DEBUGGING_ENABLED' not in os.environ,
reason="Requires Agent Debugging APIs")
This commit reintroduces the changes that were inadvertently undone and
enables the `task exec` integration tests by default so that something
like this doesn't occur in the future.

Undo reverted changes that cause `dcos task exec` to break.

---

cli/tests/integrations/test_experimental.py

This is a quick fix to get the tests passing. I will file a separate JIRA to fix the problem with `linkerd`.

The linkerd package has a syntax error; switch to hello-world

---

cli/tests/integrations/test_task.py

The newest `dcos` master includes a `.ssl` folder that needs to be accounted for when running all of the tests that look for (and account for) files in a task's sandbox. This PR updates these tests appropriately.

Update all `test_ls*` tests to accommodate new `.ssl` folder in sandbox.

---

cli/tests/integrations/helpers/common.py
cli/tests/integrations/test_task.py

Previously, this test was flaky because sometime it would come up with 5
lines and other times 7. This flakiness is due to some idiosyncrasies
with 'logrotate' where sometimes it creates a '*.logrotate.state' file
during the test run, and other times it doesn't. When it does, there
will be 7 lines in the output. When it doesn't, there will be 5.

Updated 'test_ls_long()' to look for a range of lines.

---

cli/dcoscli/data/help/marathon.txt

The first one triggers a 404 and the second one has an unexisting anchor.

Update help links for dcos marathon add

---

cli/dcoscli/util.py
cli/tests/integrations/test_experimental.py
cli/tests/integrations/test_job.py
cli/tests/integrations/test_marathon_groups.py
cli/tests/integrations/test_marathon_pod.py

3e66e1246ff9d35afb275d083a9c96d2bd51776b added an explicit error message for invalid subcommand usage.
This change rephrases it to make it clear that the subcommand exists but is being misused.
https://jira.mesosphere.com/browse/DCOS_COMMUNITY-95

update error message for invalid subcommand usage

---

dcos/subcommand.py

https://jira.mesosphere.com/browse/DCOS_OSS-811

subcommand: add exception message to _generic_error

---

ci/Jenkinsfile-linux-binary
ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-binary
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-binary
ci/Jenkinsfile-windows-integration

There is now a subfolder called `ci` under which Jenkinsfiles for each of our various builds can be found (`{linux, mac, windows}-binary` and `{linux, mac, windows}-integration-tests`). Right now they are straight copies of the old Jenkinsfile, with the unnecessary stuff from building on other platforms / configurations stripped out. There is *alot* of cleanup / optimization that can happen from here. I just wanted to start with the smallest incremental change from the original as possible.
The build jobs these new Jenkinsfiles are linked to can be found here:
https://jenkins.mesosphere.com/service/jenkins/job/DCOS-CLI/job/mesosphere-dcos-cli/

Refactored top level Jenkinsfile into smaller Jenkinsfiles.

---

cli/dcoscli/node/main.py
cli/dcoscli/package/main.py
cli/tests/integrations/helpers/common.py
cli/tests/integrations/test_cluster.py
cli/tests/integrations/test_package.py

Prior to 1254a2f2b5210c68d86f4b16c4c6b16ad2e911ae and when running
"dcos cluster setup" command as non-interactive, the process would run
and ask for user input forever.
This adds an integration test which fails if the process doesn't exit by
itself with an error within 30 seconds.
https://jira.mesosphere.com/browse/DCOS-15590

Add a test against infinite prompt during cluster setup

---

dcos/errors.py
dcos/http.py
tests/test_errors.py

This also fixes an issue where a string message is passed instead of a Response object.
cf. https://jira.mesosphere.com/browse/DCOS-16144

Add a message argument to DCOSAuthenticationException

---

cli/dcoscli/package/main.py
cli/tests/data/helloworld-v3-stub.json
cli/tests/data/package/json/test_list_helloworld.json
cli/tests/data/package/json/test_list_helloworld_cli.json
cli/tests/data/package/json/test_package_metadata.json
cli/tests/integrations/test_package.py
dcos/package.py
dcos/util.py

When there are multiple apps from a given package, which also happens to have a subcommand, uninstalling any of these app would remove the subcommand : 
```
$ dcos package install hello-world --yes --options /path/to/options1.json
$ dcos package install hello-world --yes --options /path/to/options2.json
$ dcos package list                                                             
NAME         VERSION       APP       COMMAND      DESCRIPTION                                                   
hello-world  2.0.0-0.30.0  /hello1  hello-world  An example implementation of a stateful service using the...  
/hello2
$ dcos package uninstall hello-world --yes --app-id=/hello1
```
This PR changes the uninstall behaviour so that no subcommand is removed as long as there is at least one remaining …

don't uninstall cli subcommand when there are remaining apps

---

cli/tests/unit/test_auth.py
dcos/auth.py
dcos/packagemanager.py

When running tests locally I'm getting the following error : 
```
self = <dcos.packagemanager.CosmosPackageVersion object at 0x7f5b6fcfb4e0>, name = 'fake_pkg', package_version = '0.0.1'
url = 'http://testserver/cosmos'
def __init__(self, name, package_version, url):
self._cosmos_url = url
params = {"packageName": name}
if package_version is not None:
params["packageVersion"] = package_version
response = PackageManager(url).cosmos_post("describe", params)
self._package_json = response.json()
>       self._content_type = response.headers['content-type']
E       KeyError: 'content-type'
.tox/py35-unit/lib/python3.5/site-packages/dcos/packagemanager.py:362: KeyError
```
It seems like the content-type header is not lower-cased.
Right now these tests are not executed on CI, so that might be …

	Use a consistent case for http headers

---

dcos/http.py
dcos/util.py

```
flake8.main.application   MainProcess    814 INFO     Reporting errors
dcos/http.py:30:1: E302 expected 2 blank lines, found 1
dcos/http.py:59:1: E302 expected 2 blank lines, found 1
dcos/util.py:54:1: E302 expected 2 blank lines, found 1
flake8.main.application   MainProcess    815 INFO     Found a total of 20 violations and reported 3
ERROR: InvocationError: '/home/bamarni/dcos/dcos-cli/.tox/py35-syntax/bin/flake8 --verbose dcos tests setup.py'
_____________________________________ summary _____________________________________
ERROR:   py35-syntax: commands failed
```
Once #1038 is addressed we will be able to add the dcos syntax/unit test suite to CI (cf. https://jira.mesosphere.com/browse/DCOS_OSS-1543).

fix code style errors on dcos package

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
tests/test_cluster.py

https://jira.mesosphere.com/browse/DCOS_OSS-1543
Unit tests were not passing on windows because of a wrong directory separator used during an equality assertion.

CI: Run syntax / unit tests of the dcos package

---

cli/tests/integrations/test_experimental.py
cli/tests/integrations/test_package.py

- Use pytest.raises instead of try / except / assert
- don't t assert during exception handling (as it can cause an unreadable error trace)
- Use util.tempdir() instead of a custom function

Simplify some tests

---

cli/dcoscli/job/main.py

fixes bug found on schedule update which force schedules to be in an array.  
now there can be 1 or 1 in an array.

allow metronome schedule updates to not require an array

---

cli/dcoscli/job/main.py

the job list query was missing the embedded schedules in order to determine if the job is scheduled or not.  fix.

job list needs the schedules to determine if the status is scheduled

---

ci/Jenkinsfile-linux-binary
ci/Jenkinsfile-mac-binary
ci/Jenkinsfile-windows-binary

The default checkout notably causes issues when the PR branch cannot be merged as fast-forward. Then git tries to create a merge commit and fails because Jenkins builders don't have a git name and email properly configured. Last time it happened was on this PR : [#1058](https://github.com/dcos/dcos-cli/pull/1058#issuecomment-329193425).
Aligning the git checkout with the one from integration tests Jenkinsfile seems to fix this issue. The branch of this PR for example misses the last commit from the current master branch.
cf. https://jira.mesosphere.com/browse/DCOS_OSS-1634

DCOS-CLI binary CI builds sometimes fail with git error : "Please tell me who you are."

---

README.rst
ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
cli/tests/integrations/helpers/common.py
cli/tests/integrations/test_node.py

Previously, we relied on custom cloud formation templates to launch the DC/OS clusters required by our CI jobs. This commit updates all of our integration test Jenkinsfiles to instead use dcos-launch in "onprem" mode with the proper configuration setup instead of running against these custom templates.
As part of this PR, it became obvious that some extra work was needed to get our CI system working properly for our various SSH tests with this change. The commits that fix those issues are included in this PR.

Updated Jenkinsfiles to remove reliance on custom CF templates and fix `ssh` tests.

---

cli/tests/integrations/test_config.py
dcos/config.py

Without these changes, one can get the following :
``` shell
$ dcos config set coree.ssl_verify true
'coree' is not a dcos command.
$ dcos config set help.sf jhfshf
Traceback (most recent call last):
File "cli/dcoscli/subcommand.py", line 103, in run_and_capture
File "cli/dcoscli/config/main.py", line 18, in main
File "cli/dcoscli/util.py", line 24, in wrapper
File "cli/dcoscli/config/main.py", line 33, in _main
File "dcos/cmds.py", line 43, in execute
File "cli/dcoscli/config/main.py", line 91, in _set
File "dcos/config.py", line 245, in set_val
File "dcos/config.py", line 455, in get_config_schema
File "cli/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1173, in resource_string
File "cli/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1605, in …
```

Make a "dcos config" error message more explicit

---

cli/dcoscli/data/help/package.txt

The first commit updates the `--all` option description, I think we mean `applications` instead of `packages` here.
The second one is about making those options mutually exclusive, as it doesn't make sense to use them together. So when using both of them, one would get an `Invalid subcommand usage` error printed out.

Clarifications about --all and --app-id

---

README.rst
ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
cli/dcoscli/cluster/main.py
cli/dcoscli/config/main.py
cli/dcoscli/main.py
cli/tests/data/cluster_migration/dcos.toml
cli/tests/data/dcos.toml
cli/tests/integrations/helpers/common.py
cli/tests/integrations/test_cluster_migration.py
cli/tests/integrations/test_config.py
dcos/config.py
tests/test_config.py

It nows only changes the config value and unsets the acs token, this
ensures backward compatibilty is preserved.
This command is still deprecated and users are encouraged to switch to
the "dcos cluster setup" command.
https://jira.mesosphere.com/browse/DCOS-16088
```
Setup flow for new users of the 0.4.x CLI:
$ export DCOS_CONFIG=<path/to/config> (optional)
(default when not set is ~/.dcos/dcos.toml)
$ dcos config set core.dcos_url <url>
$ dcos config set core.ssl_verify [“true” | “false” | <path/to/ca_cert>]
$ dcos auth login
(generates  / updates global config at $DCOS_CONFIG where all settings are set)
Setup flow for new users of the 0.5.x CLI:
$ export DCOS_DIR=<path/to/config_dir> (optional)
(default when not set is ~/.dcos)
$ dcos cluster setup <url>
(generates / updates per cluster …
```

Revert "config set core.dcos_url" to its old behaviour

---

dcos/http.py

Currently, in case of an unreachable cluster, multiple commands would hang indefinitely (eg. "dcos node", "dcos package list", etc.).
This makes the default timeout for http.request() to be 5 seconds.
From http://docs.python-requests.org/en/master/user/quickstart/#timeouts : 
> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely.
I'd like to retry the CI a few times with this, as this might cause flakiness... Maybe we would need an environment variable to overwrite this default.

[http] always use a timeout by default

---

cli/dcoscli/cluster/main.py
cli/tests/integrations/helpers/common.py
cli/tests/integrations/test_cluster.py

Here are a few fixes relative to `test_setup_noninteractive`, which we have seen failing occasionally on CI.
The main problem here is that we were not stopping the flow whenever the user didn't confirm the certificate fingerprint : 
``` bash
$ dcos cluster setup http://dcos.snakeoil.mesosphere.com </dev/null
SHA256 fingerprint of cluster certificate bundle:
8B:C0:40:62:2F:45:52:3E:EA:7B:38:C0:CE:D8:AB:15:2A:A8:BA:2C:3F:D7:B7:D7:65:B5:03:37:D3:E4:D3:17 [yes/no] '' is not a valid response.
SHA256 fingerprint of cluster certificate bundle:
8B:C0:40:62:2F:45:52:3E:EA:7B:38:C0:CE:D8:AB:15:2A:A8:BA:2C:3F:D7:B7:D7:65:B5:03:37:D3:E4:D3:17 [yes/no] '' is not a valid response.
SHA256 fingerprint of cluster certificate bundle:
8B:C0:40:62:2F:45:52:3E:EA:7B:38:C0:CE:D8:AB:15:2A:A8:BA:2C:3F:D7:B7:D7:65 …
```

fixes relative to test_setup_noninteractive

---

cli/dcoscli/node/main.py
cli/dcoscli/tables.py
cli/tests/integrations/test_node.py
cli/tests/unit/data/node.txt
cli/tests/unit/data/task.txt
dcos/util.py

Add 2 new fields: `REGION` and `ZONE` to `dcos node` and `dcos task` output
[DCOS-17719](https://jira.mesosphere.com/browse/DCOS-17719)

show fault domain in node and task subcommand output

---

ci/Jenkinsfile-linux-binary
ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-binary
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-binary
ci/Jenkinsfile-windows-integration

This PR removes custom git checkouts for our jobs, instead I've configured them appropriately on Jenkins side directly. Essentially I've made them to merge master before building, and tweaked some options not to make it fail (the shallow clone with no depth could cause merge error because of unrelated history, I've set the depth to 50, it also needed a git identity to create the merge commit without failing with "Please tell me who you are", I've set it to the dummy "Jenkins <jenkins@example.com>").

Merge master before running a PR build

---

cli/dcoscli/cluster/main.py

The environment variable would currently be discarded in favor of the mandatory argument, however it might override again on a different command.
Printing a warning there could save the user from potential unexpected errors on next commands.
https://jira.mesosphere.com/browse/DCOS-15947

Warn if DCOS_URL is set during "dcos cluster setup"

---

ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration

This makes sure ~/.dcos an /etc/hosts are cleaned-up after tests.

Clean-up after mac integration tests

---

cli/dcoscli/package/main.py
cli/tests/integrations/test_package.py

This triggers a hard failure instead of the deprecation whenever `--app-id` is passed for installing a package, and updates the integration test suite accordingly.

fail in case the deprecated --app-id option is used for install (closes #463)

---

dcos/auth.py
dcos/util.py

Otherwise users might see warning messages while they are prompted for
the token.
cf. https://jira.mesosphere.com/browse/DCOS_OSS-1508
cf. https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/

Ignore outputs while opening a browser window

---

cli/dcoscli/cluster/main.py
cli/tests/unit/test_cluster.py

If it works there is no need to download and use the custom CA. This usually happens when we're dealing with a load-balancer or when a custom CA has already been added to the system.
With the Python library we're using (requests), specifying a path to a custom CA would ignore the default CA bundle in the system, so setting-up a cluster through a load balancer endpoint with a well-known CA (eg. Digicert) was previously failing without this change.
https://jira.mesosphere.com/browse/DCOS-19040

Don't use custom CA if HTTPS works out of the box

---

cli/requirements.txt
cli/setup.py
cli/tests/integrations/helpers/marathon.py
cli/tests/integrations/test_marathon_debug.py
setup.py

fixing marathon_debug tests.  
reduce integration test time and tests retry assuming eventually true expectations.  
fixed regex to not be dependent on cluster sizes.  
added retrying lib

 Fix Marathon Debug Test

---

dcos/util.py

Symbol names for outputs might differ from one OS to the other. While this works on Linux this was failing on a Macbook Pro, even though it passed on our Mac CI somehow.
As we don't really need this (it was made to make the silencing more robust), we can just remove it.
https://jira.mesosphere.com/browse/DCOS_OSS-1760

Don't flush C buffers in the silent_output contextmanager

---

cli/dcoscli/data/help/marathon.txt
cli/dcoscli/marathon/main.py

adding quiet mode to match job functionality to get list of ids

Marathon list ID only Mode

---

cli/dcoscli/cluster/main.py
cli/dcoscli/main.py
cli/tests/integrations/test_cluster.py
cli/tests/unit/test_cluster.py
dcos/cluster.py

This might be too short in case of network latency or if for any reason
the cluster is not very responsive but still works fine. In such cases
commands like "cluster setup" or "cluster --version" might fail.
There is already a 5 seconds timeout by default that we can rely on.
https://jira.mesosphere.com/browse/DCOS_OSS-1763

Remove the hardcoded 1 second timeout for some HTTP calls

---

cli/tests/integrations/test_cluster.py
dcos/cluster.py
tests/test_cluster.py

get_clusters() shoudln't consider any entry inside the clusters dir as a potential cluster, this PR makes sure it only accepts directories with a proper uuid.
Currently : 
>$ dcos cluster list 
NAME CLUSTER ID VERSION URL
a8b53513-63d4-4059-8b08-fde4fe1f1a83* a8b53513-63d4-4059-8b08-fde4fe1f1a83 1.9.1 https://dcos.snakeoil.mesosphere.com
$ touch ~/.dcos/clusters/.DS_Store 
$ dcos 
Cannot create file [/home/bamarni/.dcos/clusters/.DS_Store/dcos.toml]: [Errno 20] Not a directory: '/home/bamarni/.dcos/clusters/.DS_Store/dcos.toml'
https://jira.mesosphere.com/browse/DCOS_OSS-1782

Cluster directory should tolerate external files

---

cli/tests/unit/test_task.py
dcos/mesos.py

(DCOS-19379)[https://jira.mesosphere.com/browse/DCOS-19379]
with fault domain enabled
if fault domains are disabled, no additional fields will be added.

include region/zone in task subcommand with --json option

---

dcos/mesos.py

As this command relies on a long-running HTTP connection using chuncked transfer encoding, it is common to have no data to read from the server for an undefined period of time.
This happens for example when opening a shell session and not typing anything.
https://jira.mesosphere.com/browse/DCOS_OSS-1827
This problem was introduced in #1052.

Disable HTTP timeouts for dcos task requests

---

cli/dcoscli/metrics.py
cli/tests/unit/test_task.py

This PR fixes [DCOS-19009](https://jira.mesosphere.com/browse/DCOS-19009)
Running `dcos task metrics details <task-id>` does the following:
1. requests container metrics from `.../metrics/v0/containers/<container-id>`
1. requests app metrics from `.../metrics/v0/containers/<container-id>/app`
1. joins the two and prints them out in a table
In some cases, container metrics are not present and the dcos-metrics API returns a 204 empty. We were assuming in those cases that there were also no app metrics. Unfortunately, that is not correct in cases of executors, as in DC/OS SDK frameworks like cassandra and kafka. 
With this PR, we catch the empty case and poll app metrics as well.

Show executor metrics

---

cli/dcoscli/data/help/package.txt
cli/dcoscli/package/main.py
dcos/auth.py
dcos/packagemanager.py
dcos/subcommand.py
tests/test_packagemanager.py

For the `package install` command, the --app-id flag used to trigger a warning, it then failed with an explicit error. This PR removes it completely.

Remove verbose failure for the deprecated --app-id

---

cli/dcoscli/log.py
cli/dcoscli/node/main.py
cli/dcoscli/service/main.py
cli/dcoscli/task/main.py
cli/tests/unit/test_node.py
cli/tests/unit/test_task.py

affected subcommands:
If DC/OS cluster has the `LOGGING_V2` capability, dcos-cli should use [dcos-log v2](https://docs.google.com/document/d/1Z2gWi1H7lc3nNGqLUU9Hecvm9EyPLI-6t3uK1ANlHyA/edit#), otherwise based on the logging strategy mesos files API or dcos-log v1 will be used.

add support for dcos-log v2

---

cli/dcoscli/auth/main.py
cli/dcoscli/data/help/auth.txt
cli/tests/unit/test_auth.py
dcos/auth.py
dcos/http.py

The `dcos cluster setup` command accepts a `--provider` argument, however it is currently not possible to see all available providers for a given cluster, as the command for this assumes an already configured cluster.
This adds an optional `dcos_url` argument to `dcos auth list-providers`.
https://jira.mesosphere.com/browse/DCOS_OSS-1817

 Accept an URL argument to `dcos auth list-providers`

---

cli/dcoscli/data/help/node.txt
cli/dcoscli/node/main.py
cli/tests/integrations/test_node.py
dcos/mesos.py

This adds a `dcos node decommission` command which takes as argument an agent id. It will then mark it as gone using the Mesos operator API.
Currently the integration test is skipped because it requires the opposite of that action in order to put the cluster in a proper state again after that test.
cf. https://jira.mesosphere.com/browse/DCOS-18981

Add a command to mark an agent as gone

---

cli/dcoscli/config/main.py
cli/tests/integrations/test_config.py

When an environment variable overrides a config value, that command prints a comment. This causes problems if the consumer is trying to parse the output. For example : 
```
$ dcos config show core.ssl_verify
/Users/joergschad/.dcos/clusters/9e500174-57b2-4c91-b445-ef7ee99fcb5a/dcos_ca.crt
$ DCOS_SSL_VERIFY=false dcos config show core.ssl_verify
false          # overwritten by environment var DCOS_SSL_VERIFY; config file value: /Users/joergschad/.dcos/clusters/9e500174-57b2-4c91-b445-ef7ee99fcb5a/dcos_ca.crt
```
These comments would only get printed when no config name is passed. 
Fixes #1104

Never print a comment in `dcos config show [name]`

---

cli/dcoscli/job/main.py

fixed misleading message and added ability to understand what is really happening.
All removes are not the same... the remove failure always responded with:
```
dcos job remove job
Unable to remove 'job'.  It may be running.
```
this is the same message for trying to remove a non-existent job and for a job that is currently running.    Allowing the error message through allows for understanding the underlying issue:
Message are now:
```
Unable to remove'job'. Error: Job not found.
Unable to remove'job'. Changes blocked: deployment already in progress for resource..
```
This addresses Jira:  DCOS_OSS-1916

Job CLI Remove Error Message Fixed

---

dcos/metronome.py

metronome is not used externally.  
it is `job.url` according to the schema.

Bugfix: Metronome was NOT using the schema defined configuration

---

cli/dcoscli/metrics.py
cli/tests/unit/test_task.py

This PR fixes [DCOS_OSS-1828](https://jira.mesosphere.com/browse/DCOS_OSS-1828)
Previously, when the `/metrics/v0/containers/<container-id>/app` endpoint returned a 204 No Content response, we would print `No metrics found` and exit. This PR removes the error case treatment from a 204 response. Instead we check to see if any metrics were found at all and print them instead. 
This test script shows the fix working: (on master `dcos task metrics details statsd-emitter-docker` yields `No metrics found`)
```
$ dcos marathon app add https://gist.githubusercontent.com/philipnrmn/cc59c6eb92e0744552a92c941ec78fa2/raw/5edd33344b25bacd6c51f072b420ba7649e59be1/statsd-emitter-ucr.json
$ dcos marathon app add https://gist.githubusercontent.com/philipnrmn/c9a86746460cdaef6a4084badfad687d/raw/2ea920999bc …
```

Fix for missing task metrics with dockerized applications

---

dcos/cluster.py
dcos/constants.py

We support the DCOS_CLUSTER env variable since #994, we should take it into account when checking if a cluster is attached.
This is useful for automated scripts where one would want to attach to a cluster without affecting potential concurrent users (because of the shared attached file).
cf. https://github.com/dcos/dcos-cli/issues/595

Lookup for DCOS_CLUSTER to determine if a cluster is attached

---

README.rst
ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
cli/dcoscli/test/common.py
cli/dcoscli/test/constants.py
cli/tests/data/cluster_migration/dcos.toml
cli/tests/integrations/test_cluster.py
cli/tests/integrations/test_cluster_migration.py
cli/tests/integrations/test_ssl.py

dcos.snakeoil.mesosphere.com was expected to be pointing to the master's IP address (in /etc/hosts). This makes use of the IP directly through the `CLI_TEST_DCOS_URL` environment variable, which is already documented.

Remove reliance on dcos.snakeoil.mesosphere.com in tests

---

cli/tests/integrations/test_marathon.py

Marathon changed the error message for invalid versions.
A ticket has been opened : https://jira.mesosphere.com/browse/MARATHON-7954
Until this is resolved that test should be skipped.

Skip show_bad_app_version Marathon test

---

cli/dcoscli/cluster/main.py
cli/dcoscli/data/help/cluster_ee.txt
cli/tests/integrations/test_cluster.py
cli/tests/integrations/test_cluster_migration.py
cli/tox.ini
dcos/cluster.py

- Sort login providers during the `cluster link` prompt
- A LinkedCluster object might be a configured cluster
- Add --linked flag to `dcos cluster list`
- Don't error out in case no cluster is listed
- Don't rely on the http module to get cluster version

Cluster linker improvements

---

cli/dcoscli/package/main.py
cli/tests/integrations/test_package.py
cli/tests/unit/test_package_uninstall.py

By default the following message appears :
> WARNING: This action cannot be undone. This will uninstall [dcos-enterprise-cli] and delete all of its persistent data (logs, configurations, database artifacts, everything).
This is not accurate when uninstalling a CLI only package implicitly (without specifying the --cli flag).
https://jira.mesosphere.com/browse/DCOS-19010

Update prompt for confirmation when uninstalling CLI only

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration

installer would not pass exhibitor_storage_backend implicitly anymore, we
need to include it in dcos-launch config.

fix dcos-cli CI

---

cli/tests/integrations/test_package.py
dcos/cluster.py
dcos/http.py
tests/test_http.py

This leverages the tuple timeout of the requests package in order to distinguish between the connection timeout and the response read timeout.
When a timeout is passed as a numeric value, it refers to the read_timeout.
When no explicit timeout is passed, the `core.timeout` value in the config file is now used, or if not present, defaults to 180. This also refers to the read_timeout.
The connection timeout defaults to 5. In order to overwrite it, one must pass a tuple of the form `(connection_timeout, read_timeout)`.
https://jira.mesosphere.com/browse/DCOS_OSS-1956
https://jira.mesosphere.com/browse/DCOS_OSS-1957

HTTP timeout improvements

---

cli/dcoscli/metrics.py
cli/tests/integrations/test_node.py

Previously, as an outcome of `dcos node metrics summary`, the CLI reported the percentage of the disk that was available, eg 1GB (99%) for a 100GB disk.
This PR updates that calculation so we now see the used percentage, so in the above case the user would now see a disk entry of 1GB (1%). 
Additionally, I expanded the output from the --json endpoint after noticing that it only reported the total system memory and disk usage.

Improve output from metrics summary

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
cli/tox.ini

DC/OS 1.11 now requires a valid license in order to get installed. This adapts the CLI Jenkinsfiles accordingly.

Add the CI license on integration tests

---

dcos/cluster.py

I had an issue I cannot reproduce where the JSON returned by this endpoint was invalid, probably because of a wrongly installed / unhealthy cluster.
In such case it becomes impossible to run `dcos cluster list` for example as an exception is thrown, this change makes the code more resilient to this kind of problem.

Consider that dcos version metadata might be invalid

---

cli/dcoscli/test/marathon.py
cli/dcoscli/test/package.py
cli/tests/integrations/test_service.py

Using `cassandra` here started to fail as the test cluster doesn't seem to have enough resources to run it anymore.
In any case, using it for such tests is overkill. There were already an effort to move away from installing latest versions of heavy frameworks in our tests (https://github.com/dcos/dcos-cli/pull/1094).
This would also help us to move towards https://github.com/dcos/dcos-cli/pull/1097.
https://jira.mesosphere.com/browse/DCOS_OSS-2131

Use `hello-world` instead of `cassandra` in a test

---

cli/dcoscli/cluster/main.py
cli/tests/integrations/test_cluster.py

- Update a parameter pydoc description
- Don't require the cluster to be configured when unlinking
- Show an explicit error message when recreating an existing link
- Display a custom error message when unlinking an invalid cluster

Cluster link error messages improvements

---

cli/tests/integrations/test_cluster.py
dcos/cluster.py

Currently it is using `os.path`, which would use a backslash on Windows, this makes the HTTP request to fail.
Discovered while looking at https://jira.mesosphere.com/browse/COPS-2400

Properly query for DC/OS version on Windows 

---

cli/dcoscli/log.py
cli/tests/unit/test_task.py
dcos/errors.py

- add 500 response code to is_success function to handle the 500 error
in caller instead of `http` module.
- if the user encounters 500 when trying to fetch the logs, use
`DCOSUnprocessableException` to include the text with the actual error
message.

 dcos-log v2: add a custom handler for 500 error

---

cli/tests/integrations/test_marathon.py

It had been disabled in #1122, now that the Marathon version in DC/OS contains the patch, the test can be re-enabled.

Re-enable Marathon test

---

dcos/cluster.py
tests/test_cluster.py

Otherwise the name returned from the cluster linker service will take precedence over a potential custom name in the config file.
https://jira.mesosphere.com/browse/DCOS-21082

Give priority to Cluster over LinkedCluster when listing

---

cli/dcoscli/cluster/main.py
cli/tests/integrations/test_cluster.py

User test reports have shown this to be confusing, as once they configure a second cluster, they forget to attach back to the original one.
https://jira.mesosphere.com/browse/DCOS-21047

Disable self-linking

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration

Whenever a Jenkins build for the main branches fails, a notification will be posted to the #dcos-cli-ci Slack channel

Post CI failures on slack

---

cli/dcoscli/cluster/main.py
dcos/cluster.py
tests/test_cluster.py

It makes the CLI more user-friendly.
This is also similar to how the `docker` CLI works with container names / IDs.

Allow initial ID portions for cluster lookups

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration

I've added a `BRANCH_NAME=master` environment variable in the nightly build config, so we should now receive slack notifications on failures.
This patch is just about using `task_wrapper()` on the main node instead of the inner one. This would send notifications for failures during `dcos_launch` too.

Fix nightly slack notification

---

cli/dcoscli/package/main.py

Passing the `--global` flag to the `dcos package install` command
is now deprecated and support for this will be removed in 1.12.
Subcommands should always get installed for a given cluster instead.
https://jira.mesosphere.com/browse/DCOS_OSS-2157

Deprecate installation of global subcommands

---

dcos/config.py
tests/test_config.py

This env variable causes inconsistent behaviours, eg. `dcos cluster list` would display all clusters with the same name when DCOS_CLUSTER_NAME is set.
One should instead run `dcos cluster rename <cluster> <new_name>` in order to change a cluster name.
https://jira.mesosphere.com/browse/DCOS-21098

Ignore DCOS_CLUSTER_NAME env var

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
cli/dcoscli/cluster/main.py
dcos/cluster.py
dcos/config.py
tests/test_cluster.py
tests/test_config.py

- Revert "Moved cluster attachment to not lose track of attached cluster."
- Ignore DCOS_CLUSTER_NAME env var
- Update DC/OS installer credentials to use 1.11

Prepare 0.6.x

---

ci/Jenkinsfile-linux-integration
ci/Jenkinsfile-mac-integration
ci/Jenkinsfile-windows-integration
python/lib/dcoscli/tests/integrations/test_marathon.py

We experienced some tests failures due to timeout issues. This will become even more visible if we start some Jenkins builders in Europe, as they'd be making requests to AWS servers in the US thus have a higher network latency.
For reference, the default value is 180 seconds.

[WIP] Increase timeout for integration tests

---

ci/Jenkinsfile-linux-binary

It allows to get quicker feedback if something is obviously broken without the need to wait for linux-integration tests to be triggered and the costly AWS cluster to be created.

CI: Run syntax and unit tests on the linux-binary check

---

Makefile
pkg/cmd/dcos.go
pkg/config/config.go

It is automatically triggered on `make vet` or `make test`.
It also runs tests with the race detector enabled.

Add a lint target to the Makefile

---

pkg/cmd/dcos_config_show.go
pkg/config/config.go
pkg/config/marshal.go
pkg/config/marshal_test.go
pkg/config/store_test.go

- Break once a masked key is found in `config show`
- Clear dirty config fields after Marshalling
- Switch Config.timeout from int to time.Duration

Config tweaks

---

ci/Jenkinsfile-mac-binary
ci/Jenkinsfile-mac-integration

According to PyInstaller requirements :
> PyInstaller builds apps that are compatible with the Mac OS X release in which you run it, and following releases.
Building from an old enough Mac makes sure we support all versions onwards. The latest Yosemite version was released 3 years ago, so it already brings a wide range of supported MacOS versions for the CLI.
The Jenkins node has Python 3.5.5 compiled with OpenSSL 1.0.2n.
https://jira.mesosphere.com/browse/DCOS_OSS-2290

 Use mac-hh-yosemite Jenkins node for MacOS builds

---

python/lib/dcos/setup.py
python/lib/dcoscli/setup.py

latest version has a fix to successfully reconnect to the backend after timeout
[DCOS_OSS-2292](https://jira.mesosphere.com/browse/DCOS_OSS-2292)

pin latest sseclient package

---

python/lib/dcos/dcos/mesos.py
python/lib/dcoscli/dcoscli/task/main.py
python/lib/dcoscli/tests/integrations/test_task.py

Previously, there were problems with the way patterns were matched for
the task ID when calling `task exec`. Specifically, it didn't follow the
semantics indicated in the help string for (1) matching regular
expressions and (2) matching any substring within the ID, not just the
prefix of the ID.
The reason we did not adhere to these semantics is because we were
trying to match the exact semantics of `docker exec`, which only allows
prefix matching, not arbitrary regex or 'contains()' like semantics for
pattern matching the ID.
With this change, we have decided to break from the docker semantics and
use the default pattern matching semantics provided by the dcos-cli
library command for pattern matching task ids.
Unfortunately, there is a bug in this library, and regular expressions
are not …

Fixed pattern matching for task IDs in 'task exec'.

---

python/bin/env.sh

Don't run `pip install --upgrade pip` on Windows, it started to fail in
our Jenkins node and this is not the right command.
https://jira.mesosphere.com/browse/DCOS_OSS-2332
https://pip.pypa.io/en/stable/installing/#upgrading-pip
pypa/pip#1299

Use `python -m pip install -U pip` on Windows 

---

python/lib/dcoscli/dcoscli/data/help/task.txt

This makes it more precise as it accepts Unix file pattern wildcards instead of regexes.

Update `dcos task exec` help message about regexes

---

pkg/httpclient/client.go
pkg/httpclient/client_test.go

- add a default transport
- set a default timeout of 3 minutes
- fix a flaky test
- add a functional option type for Requests

Httpclient updates

---

python/lib/dcos/dcos/subcommand.py
python/lib/dcos/tests/test_subcommand.py

Depending on the user setup, they might contain an incorrect scheme.
This is because Cosmos relies in the scheme used to query admin router.
If a CLI is configured to use HTTPS but a load balancer sits in front
of admin router and does TLS termination, these URLs will use the HTTP
scheme.
Not only that it is a security concern, it would simply fail on setups
which don't support HTTPS. This is hopefully a temporary fix until we
come-up with a long-term fix in DC/OS.
Fixes #1190
https://jira.mesosphere.com/browse/COPS-3052
https://jira.mesosphere.com/browse/DCOS_OSS-2325

Rewrite Cosmos binary resource URLs when needed

---

pkg/cli/context.go
pkg/cmd/dcos_auth_listproviders.go
pkg/httpclient/client.go

It allows to create an HTTP client from a given Cluster. The client will use the cluster's TLS configuration and timeout.

Add an HTTPClient method in the cli.Context

---

pkg/cli/cluster.go
pkg/cli/context.go
pkg/cli/table.go
pkg/cmd/dcos_auth_listproviders.go
pkg/cmd/dcos_cluster.go
pkg/cmd/dcos_cluster_list.go

Same features as in the current DC/OS CLI, I have just renamed `CLUSTER ID` by `ID` in the output as the command already states that we list clusters.
Also abstracts the table creation so that we use the same for all our commands.

Add `dcos cluster list` subcommand.

---

pkg/cli/context.go
pkg/cmd/dcos_auth_listproviders.go
pkg/httpclient/client.go

This relies on the httputil package to dump requests and reponses, the INFO logging level displays requests/responses without the body while the DEBUG level displays them.
Eg. :
```
$ dcos -v auth list-providers https://dcos.example.com
INFO[0000] Outgoing request:
GET /acs/api/v1/auth/providers HTTP/1.1
Host: dcos.example.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
INFO[0000] Incoming response:
HTTP/1.1 200 OK
Content-Length: 531
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 20 Apr 2018 13:28:19 GMT
Server: openresty
PROVIDER ID                           AUTHENTICATION TYPE
dcos-users     Log in using a standard DC/OS user account (username and password)
dcos-services  Log in using a DC/OS service user account (username and private key)
```

Add logs for HTTP requests and responses

---

pkg/cli/context.go
pkg/cmd/dcos_auth_listproviders.go
pkg/httpclient/client.go

- Use ctx.Logger() instead of ctx.Logger
- Update an incorrect log message

Fix bad rebase

---

pkg/cmd/auth/auth.go
pkg/cmd/auth/auth_listproviders.go
pkg/cmd/cluster/cluster.go
pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_list.go
pkg/cmd/cluster/cluster_remove.go
pkg/cmd/cluster/cluster_rename.go
pkg/cmd/config/config.go
pkg/cmd/config/config_set.go
pkg/cmd/config/config_show.go
pkg/cmd/config/config_show_test.go
pkg/cmd/config/config_unset.go
pkg/cmd/dcos.go

Otherwise the directory will contain many files in the future,
especially once tests are added.
Having a single command per file still allows to quickly jump to a
command code, but they are now in sub-packages.
```
/cmd                               
├── auth                              
│   ├── auth.go                       
│   └── auth_listproviders.go         
├── cluster                           
│   ├── cluster.go                    
│   ├── cluster_attach.go             
│   ├── cluster_list.go               
│   ├── cluster_remove.go             
│   └── cluster_rename.go             
├── config                            
│   ├── config.go                     
│   ├── config_set.go                 
│   ├── config_show.go                
│   ├── config_show_test.go …
```

Move subcommands to their own packages

---

python/lib/dcos/dcos/config.py

This came-up multiple times, when running `dcos config set` commands and
no cluster is currently attached, a stack trace is shown :
TypeError: join() argument must be str or bytes, not 'NoneType'
This change prevents that stack trace to be shown.
https://jira.mesosphere.com/browse/COPS-2857
https://jira.mesosphere.com/browse/DCOS_OSS-2319

Print a clear error when no cluster is attached

---

pkg/cli/context.go
pkg/cmd/auth/auth_listproviders.go
pkg/httpclient/client.go
pkg/login/login.go
pkg/login/login_test.go
pkg/login/provider.go

This introduces a login package and implements the auth header challenge as a fallback solution when the `/acs/api/v1/auth/providers` endpoint is not available.
This allows eg. to list providers with DC/OS OSS :
```
$ dcos auth list-providers http://54.202.72.66
PROVIDER ID                     LOGIN METHOD                      
dcos-oidc    Log in using OpenID Connect (Google, GitHub, or Microsoft)
```
With DC/OS EE 1.7/1.8 : 
```
$ dcos auth list-providers http://54.244.69.190
PROVIDER ID                             LOGIN METHOD                             
dcos-users   Log in using a standard DC/OS user account (username and password)
```

Support the auth header challenge to detect login providers

---

Gopkg.lock
Gopkg.toml
cmd/dcos/main.go
pkg/cli/context.go
pkg/cli/environment.go
pkg/prompt/prompt.go
pkg/prompt/prompt_test.go

This package provides helpers to ask for interactive input. It currently supports text input, password and choosing from a list.
Usage : 
``` go
prompt := prompt.New(os.Stdin, os.Stdout)
username := prompt.Input("Username: ")
pass := prompt.Password("Password:")
choices := []string{"a", "b", "c"}
i, err := prompt.Select("Please choose:", choices)
if err != nil {
return err
}
choice = choices[i]
```

Add a prompt package

---

api/cli.go
pkg/cli/context.go
pkg/open/open.go
pkg/open/open_darwin.go
pkg/open/open_linux.go
pkg/open/open_windows.go

It allows to open files or URLs in user's preferred application. It is mainly useful to trigger auth flow in browsers.
This implementation is based on what https://github.com/skratchdot/open-golang does, except that it introduces an interface and has logging capabilities.

Add an open package

---

python/lib/dcoscli/dcoscli/data/help/job.txt

Either job_run_id OR --all flag is required for `dcos job <job_id>`
https://jira.mesosphere.com/browse/DCOS_OSS-3302

Job Kill Requires Argument

---

api/cli.go
pkg/cmd/auth/auth.go
pkg/cmd/auth/auth_listproviders.go
pkg/cmd/cluster/cluster.go
pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_list.go
pkg/cmd/cluster/cluster_remove.go
pkg/cmd/cluster/cluster_rename.go
pkg/cmd/config/config.go
pkg/cmd/config/config_set.go
pkg/cmd/config/config_show.go
pkg/cmd/config/config_unset.go

open.Opener is an interface, this also updates commands to use the
interface so that other mistakes like this get detected, it would also
allow to pass mocks during tests.

Fix the context interface and use it in commands

---

STYLEGUIDE.md

This style guide is to help align internal and external CLI plugins going forward so the experience is consistent for DC/OS users.

Create CLI Style Guide

---

CONTRIBUTING.md
README.md

This PR adds a link to the CLI style guide making it clear to reference the style guide before contributing.

Add style guide links to readme 

---

design/setup.md

This design page explains how the `dcos cluster setup` flow is designed from a high-level perspective, the main steps are:
- how to detect the DC/OS security mode and when it is useful to do so
- when using HTTPS, setup the TLS configuration for the CLI to communicate with the cluster
- trigger a login
- get cluster ID and cluster name
- store the cluster config
- attach the CLI to the cluster

Add a design page for `dcos cluster setup`

---

cmd/dcos/main.go

It displays the CLI as well as installed plugins versions.
There are also version information regarding the currently attached DC/OS cluster, if any.
https://jira.mesosphere.com/browse/DCOS_OSS-3702

Support the `--version` flag

---

pkg/cli/context.go
pkg/cmd/dcos.go
pkg/httpclient/client.go
pkg/log/formatter.go
pkg/log/formatter_test.go

It just keeps the log entry message and appends a newline to it. This makes them more user-friendly in the terminal.
Before : 
```
INFO[0000] Log message.
```
After : 
```
Log message.
```
https://jira.mesosphere.com/browse/DCOS_OSS-3746

 Add a custom log formatter

---

api/cli.go
cmd/dcos/main.go

It also updates a method signature to use the interface instead of the implementation.

Add missing Input() method to api.Context

---

cmd/dcos/main.go
cmd/dcos/main_test.go
pkg/cmd/dcos.go
pkg/mock/mock.go

Having it in the pre run hook discards all the logs from the plugin manager, this is because the plugin manager is invoked while creating the cobra command tree. The hook is only invoked later while actually calling a command.
Declaring the flag outside of cobra and setting the log level directly fixes this problem.
https://jira.mesosphere.com/browse/DCOS_OSS-3822

Set the logging level outside of cobra

---

pkg/cmd/dcos.go
pkg/cmd/dcos_test.go
pkg/cmd/plugin/plugin.go
pkg/cmd/plugin/plugin_remove.go
pkg/plugin/manager.go

It allows to remove a plugin from the filesystem based on its name.
https://jira.mesosphere.com/browse/DCOS_OSS-3834

Implement "dcos plugin remove"

---

pkg/cmd/plugin/plugin.go
pkg/cmd/plugin/plugin_list.go
pkg/plugin/plugin.go

It supports table and JSON outputs.
TABLE:
$ dcos plugin list
NAME                 COMMANDS
dcos-enterprise-cli  backup license security
JSON:
```` json
$ dcos plugin list --json
[
{
"name": "dcos-enterprise-cli",
"commands": [
{
"name": "backup",
"path": "/home/bamarni/.dcos/clusters/a95bf067-2e6b-4468-ba86-0d177b226950/subcommands/dcos-enterprise-cli/env/bin/dcos-backup",
"description": "Access DC/OS backup functionality"
},
{
"name": "license",
"path": "/home/bamarni/.dcos/clusters/a95bf067-2e6b-4468-ba86-0d177b226950/subcommands/dcos-enterprise-cli/env/bin/dcos-license",
"description": "Manage your DC/OS licenses"
},
{
"name": "security",
"path": "/home/bamarni/.dcos/clusters/a95bf067-2e6b-4468-ba86-0d177b226950/subcommands/dcos-enterprise-cli/env/bin/dcos-security",
"description": …
```

Implement "dcos plugin list"

---

pkg/login/flags.go
pkg/login/flags_test.go

- Support reading username from DCOS_USERNAME env var
- Remove the --password-env login flag
https://jira.mesosphere.com/browse/DCOS_OSS-3578

`dcos auth login` changes after the sec team review

---

pkg/cli/context.go
pkg/cmd/cluster/cluster_setup.go
pkg/cmd/plugin/plugin_add.go
pkg/cosmos/client.go
pkg/cosmos/client_test.go
pkg/httpclient/client.go
pkg/plugin/manager.go
pkg/setup/flags.go
pkg/setup/setup.go

Unless the --no-plugin flag is passed, `dcos cluster setup` will attempt
to install the dcos-enterprise-cli plugin. The dcos-enterprise-cli
plugin is only installed when the metadata endpoint explicitly specifies
that it is an enterprise variant.
The plugin resources are retrieved through the Cosmos client.
The plugin manager currently only supports installing a ZIP plugin from
the filesystem. Support for remote and bin resources will be added with
the future `dcos plugin add` command.
https://jira.mesosphere.com/browse/DCOS-20502

Auto-install dcos-enterprise-cli during cluster setup

---

pkg/cmd/auth/auth_listproviders.go
pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_link.go
pkg/cmd/cluster/cluster_remove.go
pkg/cmd/cluster/cluster_rename.go
pkg/cmd/cluster/cluster_setup.go
pkg/cmd/cluster/cluster_unlink.go
pkg/cmd/config/config_set.go
pkg/cmd/config/config_show.go
pkg/cmd/config/config_unset.go
pkg/cmd/plugin/plugin_add.go
pkg/cmd/plugin/plugin_remove.go

Current usage outputs :
```
Usage:
dcos cluster setup [flags]
```
This changes them to print accepted argument names too :
```
Usage:
dcos cluster setup <url> [flags]
```

Add argument names in help menus

---

pkg/cluster/lister/filters.go
pkg/cluster/lister/lister.go
pkg/cluster/lister/lister_test.go
pkg/cmd/cluster/cluster_list.go
pkg/cmd/cluster/cluster_remove.go

It allows to remove unreachable clusters. This is useful as a clean-up
command, to get rid of outdated clusters still configured in the CLI.
https://jira.mesosphere.com/browse/DCOS_OSS-3881

Add an --unavailable option to "dcos cluster remove" 

---

pkg/cluster/lister/lister.go
pkg/cluster/lister/lister_test.go

Otherwise it causes the `dcos cluster list --json` command to print `null`.
From https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices :
>  Note that there are limited circumstances where a non-nil but
zero-length slice is preferred, such as when encoding JSON objects (a
nil slice encodes to null, while []string{} encodes to the JSON array
[]).
https://jira.mesosphere.com/browse/DCOS_OSS-3934

Don't return a nil slice when listing clusters

---

.gitignore
ci/integration-tests.groovy
tests/integration/.flake8
tests/integration/common.py
tests/integration/test_cluster.py
tests/integration/test_help.py
tests/integration/test_plugin.py
tests/launch_cluster.py
tests/requirements.txt

This adds integration tests for the new Go CLI. They are run from Jenkins and written in Python, they rely on pytest, and dcos-e2e to spin-up the DC/OS cluster.
As the test suite doesn't alter the cluster state, a single cluster is shared between all platform tests (Linux, macOS and Windows) which all run in parallel.
The main goal here is not to have full test coverage, but to setup the base structure for integration tests.
https://jira.mesosphere.com/browse/DCOS_OSS-3915

Setup integration tests

---

Makefile

Otherwise `pkg/cmd/completion/completion_data.gen.go` gets updated on every run.

Don't run go generate when building or linting

---

.appveyor.yml
.travis.yml

This removes unneeded dependencies as we don't generate Go code automatically anymore.
It also makes sure the binaries can be built before running the tests.

Public CI improvements

---

ci/release.groovy

Currently master builds get an empty version, I think it's because the git binary is missing, using `GIT_COMMIT` seems to fix it... I made the job pointing to my fork and triggered a master and a tag build.
https://downloads.dcos.io/binaries/cli/linux/x86-64/latest/dcos
```
./dcos --version
dcoscli.version=0e8d69a961f2e20b97386589de9fc5d274ef3ffb
dcos.version=1.12-dev
dcos.commit=acb6fac6f305fe8be0602f38b53e3696a277f09d
dcos.bootstrap-id=93e62c7dc049c65aca115c27a1d09e3cc178135a
```
https://downloads.dcos.io/binaries/cli/linux/x86-64/0.7.0/dcos
```
./dcos --version
dcoscli.version=0.7.0
dcos.version=1.12-dev
dcos.commit=acb6fac6f305fe8be0602f38b53e3696a277f09d
dcos.bootstrap-id=93e62c7dc049c65aca115c27a1d09e3cc178135a
```

Fix release version injection

---

pkg/httpclient/client.go
pkg/httpclient/client_test.go

This lets the httpclient dumping HTTP responses from Cosmos in debug mode.
https://jira.mesosphere.com/browse/DCOS_OSS-3994

Treat the json media type suffix as textual

---

pkg/cmd/dcos.go
pkg/fsutil/fsutil.go
pkg/plugin/manager.go
tests/integration/common.py
tests/integration/test_help.py
tests/integration/test_plugin.py

- Add a pytest cluster fixture without plugins
- Install plugins by copy instead by moving them 
- Intercept "dcos package install dcos-core-cli"

Install plugins by copy instead by moving them

---

pkg/setup/setup.go

This commit fixes, that we potentially don't wait for the
enterprise plugin to be installed correctly if the install
for the core plugin fails. We now wait for both installs
to finish before proceeding.
https://jira.mesosphere.com/browse/DCOS_OSS-4003

Fixed plugin install during cluster setup

---

pkg/cmd/dcos.go
tests/integration/test_package.py

Currently this only happens when the command is exactly `dcos package install dcos-core-cli`, but there might be additional flags such as `--yes` or `--cli`.
This also adds tests for these cases. This is still not perfect but at least provides a better support for this temporary fix.

Improve support for core CLI update interception

---

pkg/plugin/manager.go
pkg/setup/setup.go

Right now a cluster setup in verbose mode finishes like this :
Using login provider 'dcos-uid-password'.
Installing dcos-core-cli...
Installing dcos-enterprise-cli...
Installing plugin from https://.../dcos-core-cli.zip...
Installing plugin from https://.../dcos-enterprise-cli...
Added plugin to the CLI
Added plugin to the CLI
Your cluster is now setup
`Added plugin to the CLI` is not very informative as one doesn't know
which one it's about. This removes these logs and replaces `Your
cluster` with the cluster URL.

Improve some logging messages

---

cmd/dcos/main.go
pkg/cli/environment.go

This lets package users creating an OS environment more easily.
See https://github.com/mesosphere/resilience-tester/pull/5#discussion_r213241595

Add a NewOsEnvironment helper in the cli package

---

pkg/cmd/auth/auth_login.go
pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_link.go
pkg/cmd/cluster/cluster_setup.go
pkg/login/flags.go
pkg/login/flags_test.go
pkg/setup/flags.go

This gives more insights to users with unnoticed DCOS_USERNAME / DCOS_PASSWORD env vars, as otherwise they might not understand why no login credentials are being asked or why it fails to login.

Display logs when reading credentials from env vars

---

pkg/cmd/cluster/cluster_link.go
pkg/prompt/prompt.go
pkg/prompt/prompt_test.go
pkg/setup/setup.go

This adds a second argument to the Confirm() function which acts as a
fallback when users only perss [ENTER]. It is a common practice to have
prompts like:
Please confirm [Y/n]:
In such cases the capital Y indicates that it is the default action.
This also switches the fingerprint prompt to not have a default value,
as it is contains sensitive information which should explicitly be
approved by the user.
https://jira.mesosphere.com/browse/DCOS_OSS-4030

Accept default values on confirm prompts

---

.appveyor.yml
.travis.yml

Otherwise it downloads the dependencies and it might cause flakiness.

Disable go modules on CI

---

pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_attach_test.go
pkg/cmd/cluster/testdata/cluster_attach/.dcos/clusters/79893270-f9f1-4293-9225-e6e3900043a9/dcos.toml
pkg/setup/setup.go

This is about fixing a bug in the `dcos cluster attach` command. When no cluster is attached yet it was failing.
This also adds a non-regression test for it.
https://jira.mesosphere.com/browse/DCOS_OSS-4047

Fix cluster attach when no cluster is attached

---

pkg/setup/flags.go

The --ca-certs option suggests that the user already retrieved the CA by other means (eg. out-of-band). Thus it is not necessary to print for manual verification of the fingerprint.
This also keeps backwards compatibility with the previous CLI.
https://jira.mesosphere.com/browse/DCOS_OSS-4066

Don't prompt with fingerprint when using --ca-certs

---

CONTRIBUTING.md
README.md
design/README.md
design/style.md

This moves the style guide under the design folder and adds links to GNU standards (based on POSIX), which are the ones we mostly follow in our CLI and plugins.

Mention GNU standards in the CLI style guide

---

pkg/plugin/manager.go

Since we switched from renaming to copying the plugin, we should remove the temp plugin as a cleanup procedure.
This became an issue on the DC/OS integration tests suite where the new CLI caused "No space left on device" errors.
https://jira.mesosphere.com/browse/DCOS-41483

Remove temp folder after installing a plugin

---

pkg/plugin/manager.go

Currently we only remove the temporary staging dir, we should also remove ZIP artifacts from the temp folder.

Remove downloaded plugins after installation

---

pkg/cmd/dcos.go
tests/integration/test_plugin.py

Defaulting to "error" is not appropriate as with the legacy code in the core CLI some error logs show on successes too. This happens for example with the `dcos marathon app add` command.
https://jira.mesosphere.com/browse/DCOS-41826

Don't pass DCOS_LOG_LEVEL by default

---

pkg/login/flow.go

Currently we only support relative ones, this issue was raised by a DC/OS integration test.
https://jira.mesosphere.com/browse/DCOS-41848

Support absolute login start flow URLs

---

pkg/setup/setup.go
tests/integration/test_cluster.py

DCOS_ACS_TOKEN is supported in most commands except cluster setup.
This updates the setup command to skip login and use the ACS token from
this env var when it exists. This simplifies other teams scripts as they
sometimes get the ACS token by their own mean and expect the CLI to be
configured with it.
On the other hand we didn't want to add an "--acs-token" flag to the
command as we don't encourage this behaviour.
https://jira.mesosphere.com/browse/DCOS-41803

Support DCOS_ACS_TOKEN when setting-up a cluster

---

pkg/setup/setup.go
tests/integration/test_cluster.py

This is a follow-up from e830f8f98790b5807b53e187c96a690138d0a5d7.
It fixes the setup command to properly persist the ACS token when doing a setup with the DCOS_ACS_TOKEN env var. It updates the integration test accordingly.

Persist the token when doing a setup with DCOS_ACS_TOKEN

---

design/login.md
pkg/login/flow.go
pkg/login/login.go
pkg/login/login_test.go
pkg/login/provider.go

It was mistaken with browser-prompt-oidcidtoken-get-authtoken,
which requires the user to continue the flow in the browser
and then paste a login token to the terminal, as opposed to
an ACS token.
This commit clarifies the login design overview by adding that 5th login
client method and updates the code accordingly.
This was discovered while working on DCOS-41848.
https://jira.mesosphere.com/browse/DCOS_OSS-4134

Support browser-prompt-authtoken login client method

---

design/README.md
design/plugin.md
design/setup.md

This adds the plugin design doc from:
https://docs.google.com/document/d/1UN3rPhmtdpy2dz1jn3XobTJlOxQtXujbW3ExvBkmi14/edit
It removes some background section to fit more into the style of the
design pages in this repo, and updates some sections to reflect some
recent changes that were made.
The second commit is a design update to the plugin system in order to pass
additionnal env variables to plugins whenever a cluster is configured.
The main goal being to make it easier for plugins to interact with
DC/OS, as they currently have to read the config TOML file by themselves
or invoke back the `dcos` binary.

Add a plugin design doc

---

pkg/cli/context.go
pkg/setup/setup.go
tests/integration/test_cluster.py

DCOS_ACS_TOKEN is already used and planned to be used for passing
information to plugins. If a plugin does a cluster setup it would then
cause issues as the flow would try to use the current cluster's ACS
token (due to the default child process env var inheritance).
It makes sense to reduce the scope of this env var to the cluster setup
command. It remains an undocumented env var for internal usage at
Mesosphere.
https://jira.mesosphere.com/browse/DCOS_OSS-4176

Rename DCOS_ACS_TOKEN to DCOS_CLUSTER_SETUP_ACS_TOKEN

---

pkg/cmd/dcos.go
tests/integration/common.py
tests/integration/test_cluster.py
tests/integration/test_plugin.py

Follow-up PR from the plugin design update: https://github.com/dcos/dcos-cli/pull/1341
When a plugin is invoked with a cluster currently attached, a given set
of environment variables are passed.
- `DCOS_URL`: The base URL of the DC/OS cluster without a trailing slash
(eg. https://dcos.example.com).
- `DCOS_ACS_TOKEN`: The authentication token for the current user.
- `DCOS_TLS_INSECURE`: Indicates whether the CLI is configured with an
insecure TLS setup. This is set to 1 when the DCOS_URL scheme is http://
or core.ssl_verify is set to false.
- `DCOS_TLS_CA_PATH`: Unless DCOS_TLS_INSECURE=1, this env var indicates the
path to the CA bundle to verify server certificates against. When it is
not set, the system's CA bundle must be used.
https://jira.mesosphere.com/browse/DCOS_OSS-4101

Pass cluster specific environment variables to plugins 

---

design/setup.md

This updates the "setup" design page to introduce the concept of
canonical cluster URL instead of trying to detect the cluster security
mode.
This proposal is meant to tackle the following error path:
https://jira.mesosphere.com/browse/DCOS-22237
This is also currently problematic with our soak clusters redirections.

Introduce the concept of canonical cluster URL

---

design/README.md
design/corecli.md
design/plugin.md
design/setup.md

This explains when and how the CLI core bundle is used within the CLI.
It makes sure we capture in the design pages what we're doing for the following tickets:
https://jira.mesosphere.com/browse/DCOS_OSS-4202
https://jira.mesosphere.com/browse/DCOS_OSS-4186
https://jira.mesosphere.com/browse/DCOS_OSS-4187

Add a design page for the core CLI bundle

---

cmd/dcos/main.go

According to the following integration test:
https://github.com/dcos/dcos-core-cli/blob/f502187190bb583dd3b16cb56ba6ac89e158590c/python/lib/dcoscli/tests/integrations/test_dcos.py#L43
This legacy flag used to support uppercase log levels. This updates the
Go CLI to accept them as well.
https://jira.mesosphere.com/browse/DCOS_OSS-4189

Support uppercase levels on the --log-level flag

---

pkg/cmd/dcos.go

Adds custom help function to allow plugins to show proper help messages when `dcos help <plugin>` is called.

Plugin help

---

Makefile

Because we're cross-compiling from a Linux jenkins builder and cgo is
disabled when cross-compiling, our Darwin and Windows CLIs don't rely on
cgo while the Linux one might.
Explicitly passing CGO_ENABLED=0 makes sure it is also disabled on
Linux.

Disable cgo

---

pkg/setup/setup.go
tests/integration/test_cluster.py

When using the `--insecure` option, the CLI should not verify server certificates. This should also be the case when the certificate is for another host than the one in use.
https://jira.mesosphere.com/browse/DCOS_OSS-4292

Skip certificate validation when using --insecure

---

.appveyor.yml
.travis.yml
Dockerfile

It should be referred to as golang.org/x/lint/golint instead.
This started to fail with: https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58

Fix golint installation

---

README.md
ci/release.py

This updates the CLI release artifacts according to:
https://docs.google.com/document/d/1NotMmTXXU7kmjV9u-EkIP9RTVYj9Vmok0_w9R8kA-7Q
Additionaly, it continuously publishes the latest commit to master to:
https://downloads.dcos.io/cli/testing/binaries/dcos/<os>/<arch>/master/dcos{.exe}
https://jira.mesosphere.com/browse/DCOS_OSS-4278

Update CLI artifacts

---

ci/copy-release.py

This moves the script out of the core CLI.
https://github.com/dcos/dcos-core-cli/pull/66
https://jira.mesosphere.com/browse/DCOS_OSS-4278

Add a CI script to copy the CLI release

---

design/login.md
design/setup.md
pkg/login/login.go
pkg/setup/setup.go

This makes it so that `dcos cluster setup` of a cluster without authentication will not fail. `dcos auth login` and `dcos auth list-providers` will fail however but considering that a cluster without auth has no use for either of these, that seems like an acceptable tradeoff.

Fix handling for clusters with `oauth_enabled: false`

---

design/login.md
pkg/login/flow.go

Follow-up from https://github.com/dcos/dcos-cli/pull/1338
This changes the browser-prompt_authtoken client method to expect a 200
or 403 status code in case of a valid token instead of accepting
anything else than a 401. Otherwise it should also have been checking
for 50X status codes.
This is the same behavior as the Python CLI:
https://github.com/dcos/dcos-core-cli/blob/8a51a0d05ad3ece50d1041bede5a7638f3ed13a6/python/lib/dcos/dcos/auth.py#L295

Make browser-prompt_authtoken check for 200/403 status codes

---

Makefile

The version in the Makefile is set to 1.12-patch.0 and it can be configured through a CORE_VERSION env var.
https://jira.mesosphere.com/browse/DCOS-40541

Build the CLI with 1.12-patch.0

---

ci/copy-release.groovy

This Jenkinsfile is the one copying CLI tag versions to dcos-1.XX versions.

Add missing Jenkinsfile for copying releases

---

Makefile
ci/integration-tests.groovy
tests/integration/test_corecli.py

- Use DC/OS 1.13 in integration tests
- Bundle the 1.13 testing plugin in the master builds

Update the master branch for 1.13

---

ci/requirements.txt

Github is showing a security warning about the current version being used.

Update "requests" dependency

---

design/setup.md
pkg/setup/setup.go
pkg/setup/setup_test.go

Hostnames are case-insensitive and this caused issues with some
commands.
According to https://tools.ietf.org/html/rfc4343#section-6:
For example, a user could be confused by believing that two domain
names differing only in case were actually different names.
These problems can usually be handled by using a standardized or
"canonical" form of the DNS ASCII type labels; that is, always
mapping the ASCII letter value octets in ASCII labels to some
specific pre-chosen case, either uppercase or lower case.
https://jira.mesosphere.com/browse/DCOS_OSS-4501

 Normalize canonical URL host to lowercase

---

api/cli.go
pkg/cli/context.go
pkg/cli/context_test.go
pkg/cmd/auth/auth_logout.go
pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_link.go
pkg/cmd/cluster/cluster_list.go
pkg/cmd/cluster/cluster_remove.go
pkg/cmd/cluster/cluster_rename.go
pkg/cmd/cluster/cluster_unlink.go
pkg/mock/mock.go

Prior to this patch, setting a relative DCOS_DIR would cause the CLI to
fail when invoking a plugin starting from the second invocation. It
happened because the CLI prepends the DC/OS dir to a command path when
it sees it as a relative path. When a DC/OS dir is relative, that
operation would happen at every plugin invocation and grow the path
indefinitely.
This updates the DCOSDir method to prepend the current directory in case
DCOS_DIR is a relative path. It also makes it return an explicit error
in case anything goes wrong.
https://jira.mesosphere.com/browse/DCOS_OSS-4405

Add support for relative DCOS_DIR

---

pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_attach_test.go

The issue before:
```
➜  dcos-cli (master) ✔ build/darwin/dcos cluster list
NAME                          ID                     STATUS      VERSION                                        URL
*  ronzalez-fakjz4f  f3a326bc-134d-47ab-bbf0-6260c857e7c6  AVAILABLE    1.12.0      https://34.212.25.125
ronzalez-gs0b04n  27e76b1f-f63d-4f54-8d21-ae6c38d13a9b  AVAILABLE    1.12.0      https://34.222.140.41
➜  dcos-cli (master) ✔ build/darwin/dcos cluster attach ronzalez-gs0b04n
Error: multiple matches found
```
This was because ronzalez-gs0b04n xas also a cluster linked to ronzalez-fakjz4f.

Handled case when one locally and linked cluster found when attaching.

---

pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_attach_test.go

The issue before:
```
➜  dcos-cli (master) ✔ build/darwin/dcos cluster list
NAME                          ID                     STATUS      VERSION                                        URL
*  ronzalez-fakjz4f  f3a326bc-134d-47ab-bbf0-6260c857e7c6  AVAILABLE    1.12.0      https://34.212.25.125
ronzalez-gs0b04n  27e76b1f-f63d-4f54-8d21-ae6c38d13a9b  AVAILABLE    1.12.0      https://34.222.140.41
➜  dcos-cli (master) ✔ build/darwin/dcos cluster attach ronzalez-gs0b04n
Error: multiple matches found
```
This was because ronzalez-gs0b04n xas also a cluster linked to ronzalez-fakjz4f.

[0.7] Handled case when one locally and linked cluster found when attaching.

---

pkg/login/flow.go
pkg/login/flow_test.go

In a previous commit, we used the provider ID to detect a specific
provider  available for a cluster. This was wrong, the value
`DCOSUIDPassword` we are looking for being the provider type.
We should have caught the issue with an integration test but we
had not added one due to the wish to fix the DC/OS EE CI ASAP.

[1.12] Updated login flow to detect when dcos-users provider is available.

---

ci/generate_universe_resource.py

The generate_universe_resource.py script can be used to generate
resource files for universe. It takes as argument a plugin name and a
version and uses them to download the plugins from their canonical URLs
and generate sha256 checksums accordingly.
https://jira.mesosphere.com/browse/DCOS_OSS-1797

Add a script to generate a universe resource

---

pkg/cmd/completion/completion.go

With this commit we allow users to use `dcos completion zsh` to avoid
possible confusion when generating the autocompletion script.

Added `zsh` argument to `dcos completion` top-level command.

---

pkg/cmd/completion/completion.go

With this commit we allow users to use `dcos completion zsh` to avoid
possible confusion when generating the autocompletion script.

[0.7.x] Added `zsh` argument to `dcos completion` top-level command.

---

CHANGELOG.md
Makefile

This commit prepares for a new release of the `dcos-cli`.

Updated CHANGELOG.md and bumped `dcos-core-cli` version.

---

pkg/login/login.go

With this commit we fix that the CLI only emits the `uid` value in the
login credentials when explicitly setting it. This is needed to fix a
bug when using the `browser-prompt-oidcidtoken-get-authtoken` method.
https://jira.mesosphere.com/browse/DCOS_OSS-4599

Fixed emitting empty `uid` value in login credentials.

---

pkg/login/login.go

With this commit we fix that the CLI only emits the `uid` value in the
login credentials when explicitly setting it. This is needed to fix a
bug when using the `browser-prompt-oidcidtoken-get-authtoken` method.
https://jira.mesosphere.com/browse/DCOS_OSS-4599

[0.7.x] Fixed emitting empty `uid` value in login credentials.

---

design/style.md

This adds hints on the stdout/stderr distinction in the CLI.
https://jira.mesosphere.com/browse/DCOS_OSS-4173

Add recommended practices around standard streams

---

pkg/cmd/config/config_set.go
pkg/config/config.go
pkg/config/config_test.go

When an invalid value is passed, the command now returns with an error.
https://jira.mesosphere.com/browse/DCOS-11460

 Add validation for `dcos config set core.ssl_verify`

---

ci/release.py

According to https://jira.mesosphere.com/browse/DCOS-46572, the DC/OS
1.13 CLI will have its own CLI. We'll only drop the dcos-1.XX URL
buckets for DC/OS 1.14, thus we need to have a dcos-1.13 CLI endpoint.
Once DC/OS 1.13 is released this commit needs to be reverted.

Build master commits to the dcos-1.13 CLI bucket

---

ci/verify-artifacts.py

They are now live since 0.7.7 is released.

Add latest artifacts to the verify script

---

pkg/login/login.go
pkg/login/login_test.go
tests/integration/test_auth.py

When challenging auth we must ensure the auth token is empty, otherwise
we might get a 200 and the command will fail with "Authentication
disabled".
https://jira.mesosphere.com/browse/DCOS_OSS-4660

Make sure the Auth token is empty when challenging auth

---

pkg/login/login.go
pkg/login/login_test.go
tests/integration/test_auth.py

When challenging auth we must ensure the auth token is empty, otherwise
we might get a 200 and the command will fail with "Authentication
disabled".
https://jira.mesosphere.com/browse/DCOS_OSS-4660

[backport] Make sure the Auth token is empty when challenging auth

---

ci/generate_universe_resource.py

I needed to use it with the mesosphere.io domain. Instead of adding yet
another parameter or option for the domain, this lets users pass a URL
with a placeholder for the platform.

Accept a URL pattern in generate_universe_resource.py

---

design/setup.md

This updates the plugin auto-installation design page for DC/OS 1.13.
https://jira.mesosphere.com/browse/DCOS-46572
Follow-up from https://github.com/dcos/dcos-cli/pull/1374

[design] Update default plugin auto-installation

---

pkg/internal/cosmos/client.go

The default 5 seconds during cluster setup shown some failures in CI:
https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Fmesosphere-dcos-cli%2Fintegration-tests/detail/integration-tests/178/pipeline/48/

Use a 3 minutes timeout for /package/describe

---

pkg/cli/context.go
pkg/cmd/dcos.go
pkg/internal/corecli/corecli.go
pkg/setup/setup.go
tests/integration/test_cluster.py

It also adds support for the strict deprecations mode. When it is
enabled, the CLI will fail instead of falling back to using the bundled
core plugin.
https://jira.mesosphere.com/browse/DCOS_OSS-4724

Update the deprecation message when using the bundled core plugin

---

dcos-cli.rb

Version [master](https://github.com/dcos/dcos-cli/archive/master.tar.gz)

Add homebrew formula to install `dcos-cli` via `brew`

---

dcos-cli.rb

Version [0.7.9](https://github.com/dcos/dcos-cli/archive/0.7.9.tar.gz)

[0.7.x] Add homebrew formula to install `dcos-cli` via `brew`

---

pkg/internal/corecli/corecli.go
pkg/plugin/manager.go
tests/integration/test_corecli.py
tests/integration/test_plugin.py

It was previously reading/writing/overwriting files in-place without any
synchronization mechanism.
This commit introduces a `tmp` directory inside the cluster's dir, which
is used as a staging directory for writing files before they are
eventually moved atomically to their final location.
https://jira.mesosphere.com/browse/DCOS_OSS-4843

 Make the plugin runtime safe for concurrent usage

---

CHANGELOG.md
pkg/internal/corecli/corecli.go
pkg/plugin/manager.go
tests/integration/test_corecli.py
tests/integration/test_plugin.py

It was previously reading/writing/overwriting files in-place without any
synchronization mechanism.
This commit introduces a `tmp` directory inside the cluster's dir, which
is used as a staging directory for writing files before they are
eventually moved atomically to their final location.
https://jira.mesosphere.com/browse/DCOS_OSS-4843

Make the plugin runtime safe for concurrent usage

---

pkg/cmd/auth/auth.go
pkg/cmd/cluster/cluster.go
pkg/cmd/config/config.go
pkg/cmd/dcos.go
pkg/cmd/plugin/plugin.go
tests/integration/test_auth.py
tests/integration/test_cluster.py
tests/integration/test_config.py
tests/integration/test_plugin.py

Previously, running `dcos cluster invalid-command` used to return with a
0 exit code.
This updates the CLI to return a non-zero exit code in that case, as
well as printing an error message after the help usage.
https://jira.mesosphere.com/browse/DCOS_OSS-3500

Invalid command usage should return with an error

---

CHANGELOG.md

This adds entries for the following commits, which are only on master:
- https://github.com/dcos/dcos-cli/commit/e52b5bdee44122fce468572779d0c3ab05b061af
- https://github.com/dcos/dcos-cli/commit/7053a88217a5f0c40322a058ba611e4ca79879f4
- https://github.com/dcos/dcos-cli/commit/915806a8cfd75a252f2d9f4cbece2b11b99d350c

Add missing entries to the CHANGELOG

---

pkg/setup/setup.go
tests/integration/test_cluster.py

We've extracted the job, marathon, node, package, service, and task
commands into a `dcos-core-cli` plugin which gets automatically
installed during `dcos cluster setup`.
To make this new behaviour clear to users we're displaying the new
available commands at the end of the setup flow:
```
$ dcos cluster setup ...
[...]
dcos-core-cli [================================================] 22.6 MiB / 22.6 MiB
dcos-enterprise-cli [================================================] 26.0 MiB / 26.0 MiB
New commands available: backup, job, license, marathon, node, package, security, service, task
```

Display new available commands after `dcos cluster setup`

---

ci/integration-tests-open.groovy
tests/integration/test_cluster.py
tests/integration/test_help.py
tests/integration/test_plugin.py
tests/launch_cluster.py
tests/requirements.txt

This adds support for running integration tests against DC/OS open.
In order to be enabled, we should create a new Jenkins job using the
integration-tests-open.groovy script.
https://jira.mesosphere.com/browse/DCOS_OSS-4035

Run CLI integration tests against DC/OS OSS

---

pkg/cmd/cluster/cluster_setup.go
tests/integration/test_cluster.py

This makes it clearer that the command expects a single argument which
is a cluster URL.
https://jira.mesosphere.com/browse/DCOS-52029

Improve error messages for `dcos cluster setup` args error

---

design/setup.md

This is a proposal for including running services plugins as part of the auto-installed plugins during `dcos cluster setup`.
https://jira.mesosphere.com/browse/DCOS-52182

Update plugin auto-installation page

---

.travis.yml
Dockerfile
README.md
pkg/cmd/dcos.go

This does not change our supported operating systems, Go 1.12 being the
last release supporting macOS 10.10 Yosemite.

Upgrade the CLI to use Go 1.12.

---

pkg/cluster/linker/linker.go
pkg/httpclient/client.go
pkg/httpclient/client_test.go
pkg/login/login.go
pkg/setup/setup.go

This lets callers make type assertions on the error and possibly augment error messages with additional hints.
- [DCOS_OSS-5117](https://jira.mesosphere.com/browse/DCOS_OSS-5117) Regression: CLI just prints 'HTTP 401 error' when token is expired.

Add a specific error type for HTTP errors

---

pkg/httpclient/client.go
pkg/httpclient/client_test.go

This makes it possible for package users to create errors of this type
as well.
See eg. https://github.com/dcos/dcos-core-cli/pull/255
- [DCOS_OSS-5117](https://jira.mesosphere.com/browse/DCOS_OSS-5117) Regression: CLI just prints 'HTTP 401 error' when token is expired

Export HTTP error response field

---

design/login.md

For the `dcos-oidc-auth0` login provider ID, this removes the need
to copy-paste the token between the UI / CLI by leveraging a
local webserver and the `redirect_uri` parameter.
https://developer.okta.com/blog/2018/07/16/oauth-2-command-line#the-trick-to-oauth-20-on-the-command-line
https://jira.mesosphere.com/browse/DCOS-51535

Update login design page

---

Makefile

The `install` target didn't use the vendored dependencies but would rather download all deps to the `GOPATH`. This PR fixes this.
- [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

When installing the CLI we want to use the vendored deps

---

ci/verify-artifacts.groovy
ci/verify-artifacts.py

The build was also updated to be triggered on a daily basis and after
the following builds finish:
- copy-release
- release/master
- release/0.7.x
- release/0.8.x
- core/build/1.11-patch.x
- core/build/1.12-patch.x
- core/build/1.13-patch.x
- core/build/1.14-patch.x
- enterprise/publish/1.13-patch.x
- enterprise/publish/1.14-patch.x
https://jira.mesosphere.com/browse/DCOS-55632

Send a Slack notification when artifacts are not in place

---

ci/release.py

See https://jira.mesosphere.com/browse/DCOS-55632
The scripts verifying artifacts was also updated to be triggered on a
daily basis and send slack notifications to #dcos-cli-ci to prevent this
issue from happening again in the future.

Stop pushing to "latest" on 0.7.x builds

---

CHANGELOG.md
ci/integration-tests-open.groovy
ci/integration-tests.groovy
pkg/setup/setup.go

Adds a timeout to not download the CLI plugins for the services installed in a cluster so that we do not make the `dcos cluster setup` operation longer.
- [DCOS-54232](https://jira.mesosphere.com/browse/DCOS-54232) Add timeout when auto-installing package CLIs on setup

Makes installPackageServicesPlugins an experimental feature

---

CHANGELOG.md
pkg/cmd/completion/completion.sh
pkg/cmd/config/config.go
pkg/cmd/config/config_keys.go
pkg/config/config.go
tests/integration/test_config.py

Adds a `dcos config keys` subcommand and uses it for autocompletion.
- [DCOS-53202](https://jira.mesosphere.com/browseDCOS-53202) No dcos config keys subcommand to get all the possible keys without having to check the documentation.

Added 'dcos config keys' command.

---

pkg/httpclient/client.go
pkg/httpclient/client_test.go

This adds a `Put` function to `httpclient` to allow it to send `Put` requests which will be needed by DCOS_OSS-5305 to send the proper method to the new diagnostics API.
- [DCOS_OSS-5305](https://jira.mesosphere.com/browse/DCOS_OSS-5305)

Add Put method to httpclient

---

pkg/cmd/auth/auth_listproviders.go
pkg/cmd/cluster/cluster_open.go

```
Open a cluster UI in the browser
Usage:
dcos cluster open [<cluster>] [flags]
Examples:
dcos cluster open
dcos cluster open my-cluster-1
Options:
-h, --help   help for open
```

Improve help for `dcos cluster open`

---

CHANGELOG.md
design/login.md
go.mod
go.sum
pkg/cmd/auth/auth_listproviders_test.go
pkg/login/flow.go
pkg/login/loginserver/server.go
pkg/login/loginserver/server_test.go
pkg/login/provider.go
vendor/github.com/rs/cors/.travis.yml
vendor/github.com/rs/cors/LICENSE
vendor/github.com/rs/cors/README.md
vendor/github.com/rs/cors/cors.go
vendor/github.com/rs/cors/go.mod
vendor/github.com/rs/cors/utils.go
vendor/modules.txt

For the `dcos-oidc-auth0` login provider ID, this removes the need
to copy-paste the token between the UI / CLI by leveraging a
local webserver and the `redirect_uri` parameter.
https://jira.mesosphere.com/browse/DCOS-51535
- https://jira.mesosphere.com/browse/DCOS-51535

Add support for the local login server

---

pkg/cmd/dcos.go
pkg/cmd/plugin/plugin_add.go
pkg/plugin/manager.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go
pkg/setup/setup.go
tests/integration/test_help.py
tests/integration/test_plugin.py

This returns the installed plugin when the Install() method is called.
This is useful in some cases where the caller needs to do additional
work with a plugin once it's installed, eg. print the new subcommands.
This also updates the `dcos plugin add` command to print the new
commands whenever a plugin is installed.

Return plugin after installation

---

CHANGELOG.md
design/plugin.md
pkg/cmd/dcos.go
pkg/cmd/dcos_test.go
pkg/config/config.go
tests/integration/test_plugin.py

This makes it possible for a plugin to retrieve its config values
through environment variables when it's invoked.
For example, assuming a command `foo` in a given plugin. When the
configuration file contains the `bar` config for the `foo` section,
it will be passed to it as the `DCOS_FOO_BAR` environment variable.

Pass plugin config as environment variables

---

pkg/login/flow.go
pkg/login/flow_test.go
pkg/login/login.go
pkg/login/loginserver/server.go
pkg/open/open.go

For the `dcos-oidc-auth0` login provider, when the user operates the CLI
from a container or a remote machine, the local webserver will not run
on the same machine as the browser. Later on the browser will try to
send the token to eg. `localhost:43383`, which won't be reachable.
When this situation arises, we had designed the UI to fallback to
printing the login token for copy-pasting, but once the CLI has
successfully initiated the local web server, it doesn't accept input
from STDIN at all, so the user has no chance to copy-paste the token.
This commit updates the CLI to fallback to reading from STDIN when the
browser can't be opened.
Note: as an alternative, it would have been possible to concurrently
wait for data on both the local web server and STDIN, but the current
fix is simpler …

Discard the local login server on non-desktop environment

---

.appveyor.yml
.golangci.toml
.travis.yml
Dockerfile
Makefile
cmd/dcos-test/main.go
pkg/cli/context.go
pkg/cluster/linker/linker.go
pkg/cluster/lister/lister.go
pkg/cmd/config/config_set.go
pkg/cmd/dcos.go
pkg/config/config.go
pkg/fsutil/fsutil.go
pkg/login/flow.go
pkg/login/provider.go
pkg/plugin/manager.go
pkg/setup/setup.go

Use `golangci-lint` instead of just `golint`. Fixes all reported issues.
Refs: https://github.com/dcos/dcos-core-cli/pull/349

Add golangci-lint

---

constants/timeouts.go
pkg/cli/context.go
pkg/cmd/cluster/cluster_setup.go
pkg/config/cluster.go
pkg/config/config.go
pkg/httpclient/client.go
pkg/setup/flags.go
pkg/setup/setup.go

This option will be saved in cluster `dcos.toml` and used by `ctx.HTTPClient(...)` to create http client.
See: https://github.com/dcos/dcos-cli/blob/b4a7d91628ecec93c4f4dc4ab7cb9ae7b4ccb29f/pkg/cli/context.go#L156-L175

Add timeout option for cluster setup

---

CHANGELOG.md
pkg/prompt/prompt.go
pkg/prompt/prompt_test.go

As the `prompt.Input()` function relies on a `bufio.Scanner`, it
currently scans all the lines and would only return the first one.
As the scanner is not re-used across multiple calls, this causes input
data to be discarded for later calls when there is multiline input.
As a concrete example, the following currently wouldn't work:
echo "username\npassword" | dcos auth login --provider=dcos-users
This is however not a common case as users would usually rather do:
dcos auth login --username=username --password=password

Do not comsume all input data on prompt

---

api/cli.go
cmd/dcos/main.go
pkg/cli/context.go
pkg/cluster/lister/lister.go
pkg/cmd/auth/auth_listproviders.go
pkg/cmd/auth/auth_login.go
pkg/cmd/cluster/cluster_attach.go
pkg/cmd/cluster/cluster_link.go
pkg/cmd/cluster/cluster_unlink.go
pkg/cmd/dcos.go
pkg/config/cluster.go
pkg/config/cluster_test.go
pkg/plugin/manager.go

We do not check if TLS is set up properly. When we can't read certificate or it was invalid we silently switched to insecure mode. This PR changes this behavior. Whenever HTTP Client is created it
checks for errors and returns one if necessary. The only exception are `list` and `setup` commands. List will allow user to list all clusters but call to attach will fail. `setup` uses `insecureHttpClient` by default – to download certs.
https://github.com/dcos/dcos-cli/blob/51eee402180b99bdf56ebe8356963b98807b8861/pkg/setup/setup.go#L251-L254
Fixes: https://jira.mesosphere.com/browse/DCOS-61005

Check TLS config when creating HTTP Client

---

cmd/dcos/main.go

> certifi is a library that was used in the python codebase, it does not apply anymore.
Refs:
* https://github.com/dcos/dcos-cli/pull/1513#pullrequestreview-320711349
* https://jira.mesosphere.com/browse/DCOS-61005

Fix invalid error message

---

ci/release.groovy

Master releases are failing because file already exists and unzip prompt user.
By adding `-o` we force overwrite.
See: https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Fmesosphere-dcos-cli%2Frelease/detail/master/9/pipeline#step-30-log-130

Release script unzip overrite files
